### ISSUE TITLE
Clean-up and rename the ApiChecker tool

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#1010]
Let's rename it if we are going to use it for more general purposes.

**Comment by avodovnik** [comment]
I agree. Also, since we're touching it, let's make sure we do housecleaning tasks on it, like clean-up the compiler/analyzer warnings.

**Comment by avodovnik** [comment]
@kblok How do you feel about just calling it `CLI`? If we want to differentiate from Playwright's actual CLI, we could get creative and say `CLISharp` :-)

**Comment by kblok** [comment]
This would be for internal use. We could have the suffix CLI, but I think it would be nice to have a name to reflect that it's not the dotnet tool but something for us to work with.
