### ISSUE TITLE
Support for macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by nor0x** [microsoft/playwright-sharp#1015]
i have been using Playwright-Sharp on macOS for while - however updating my system to macOS 11.0 Big Sur seemed to break my application with the following error:

```js
(node:3524) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.0
    at Object.assert (/snapshot/playwright-cli/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:125:13)
    at Object.downloadBrowserWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:150:17)
    at async validateCache (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:99:9)
    at async Object.installBrowsersWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:56:5)
(node:3524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The error is caused either by `Playwright.InstallAsync();` or `Playwright.CreateAsync();` because it gets thrown before i can launch a browser i.e. `playwright.Webkit.LaunchAsync(...)`.

I saw that there is the same issue in the upstream repository https://github.com/microsoft/playwright/issues/2789 so maybe it's easy to get this into Playwright-Sharp 🤞

thank you!

**Comment by kblok** [comment]
@nor0x tests are passing locally (I'm on Big Sur). Hopefully, we are shipping 0.162.0 this week.

**Comment by sylvesteraswin** [comment]
I am getting the below error in Big Sur, do you think it would also be fixed with the new version?

```bash
browserType.launch: No executable path is specified. Pass "executablePath" option directly.
```

**Comment by kblok** [comment]
@sylvesteraswin I believe v0.162.0 should fix that. We'll get that this week, hopefully.

**Comment by kblok** [comment]
@nor0x, @sylvesteraswin could you folks take a look at v0.162.0?

**Comment by nor0x** [comment]
i can confirm that the macOS 11.0 compatibility issue is solved by using 0.162.0 🥳
unfortunately i'm experiencing a new issue now, which didn't occur in 0.152.0 (on macOS 10.15)

i'm doing a regular `await Playwright.InstallAsync();` which throws the following exception

```
PlaywrightSharp.PlaywrightSharpException: Driver not found neither at '/Users/Dev/MyApp/Demo/MyApp.Products.Demo.MacOS/bin/Debug/MyApp.app/Contents/MonoBundle/runtimes/osx/native/playwright-cli', nor '/Users/Dev/MyApp/Demo/MyApp.Products.Demo.MacOS/bin/Debug/MyApp.app/Contents/MonoBundle/playwright-cli'
  at PlaywrightSharp.Transport.Connection.GetExecutablePath () [0x00183] in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:273 
  at PlaywrightSharp.Transport.Connection.GetProcess (System.String driverExecutablePath) [0x00000] in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:212 
  at PlaywrightSharp.Transport.Connection.InstallAsync (System.String driverPath, System.String browsersPath) [0x0003d] in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:83 
```

**Comment by kblok** [comment]
Hey @nor0x. I’m sorry about that. I see a MonoBundle in your path. How are you deploying the app?

**Comment by nor0x** [comment]
@kblok in this case i'm using Playwright in an Xamarin.Mac app

**Comment by kblok** [comment]
Cool. I’ll take a look at that. Could you share the main part of your csproj so we're sure we share the same scenario? (target framework, main packages, etc)
You can send me an email if you don't feel comfortable sharing that in public.

**Comment by nor0x** [comment]
here is the csproj of my Xamarin.Mac app

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
        <OutputType>Exe</OutputType>
        <RootNamespace>MyApp.MacOS</RootNamespace>
        <AssemblyName>MyApp</AssemblyName>
        <TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
        <TargetFrameworkIdentifier>Xamarin.Mac</TargetFrameworkIdentifier>
        <MonoMacResourcePrefix>Resources</MonoMacResourcePrefix>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug</OutputPath>
        <DefineConstants>DEBUG;</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <EnableCodeSigning>false</EnableCodeSigning>
        <CreatePackage>false</CreatePackage>
        <EnablePackageSigning>false</EnablePackageSigning>
        <IncludeMonoRuntime>false</IncludeMonoRuntime>
        <UseSGen>true</UseSGen>
        <UseRefCounting>true</UseRefCounting>
        <PlatformTarget>x86</PlatformTarget>
        <HttpClientHandler></HttpClientHandler>
        <LinkMode></LinkMode>
        <XamMacArch></XamMacArch>
        <AOTMode>None</AOTMode>
        <CodeSignEntitlements>Entitlements.plist</CodeSignEntitlements>
        <UseHardenedRuntime>true</UseHardenedRuntime>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="Xamarin.Mac" />
        <PackageReference Include="Xamarin.Essentials">
          <Version>1.6.0-pre2</Version>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Xamarin.Forms">
            <Version>4.8.0.1269</Version>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <None Include="Info.plist" />
        <None Include="Entitlements.plist" />
    </ItemGroup>
  
    <ItemGroup>
        <InterfaceDefinition Include="Main.storyboard" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\MyApp.BrowserLib\MyApp.BrowserLib.csproj">
          <Project>{0d1bc5b1-909a-4d20-a6fe-dc03d5fe9ee7}</Project>
          <Name>MyApp.BrowserLib</Name>
        </ProjectReference>
    </ItemGroup>
    <Import Project="$(MSBuildExtensionsPath)\Xamarin\Mac\Xamarin.Mac.CSharp.targets" />
</Project>

```

The playwrigh code lives in `MyApp.BrowserLib` which is a referenced .netstandard library with the following csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PlaywrightSharp" Version="0.162.0" />
  </ItemGroup>
</Project>
```

**Comment by kblok** [comment]
@nor0x, it seems to be an issue with the NuGet restore process. As you can see there, NuGet is copying the runtimes from the platform win-x64. That's not something we coded. We are relying on NuGet there.

```
  CandidateAssemblyFiles:
      /Users/neo/Documents/Coding/Personal/Xamarin.Mac.PlaywrightSharpTest/packages/PlaywrightSharp.0.162.0/build/netstandard2.0/../../runtimes/win-x64/native/ffmpeg-win64.exe
      /Users/neo/Documents/Coding/Personal/Xamarin.Mac.PlaywrightSharpTest/packages/PlaywrightSharp.0.162.0/build/netstandard2.0/../../runtimes/win-x64/native/playwright-cli.exe
      /Users/neo/Documents/Coding/Personal/Xamarin.Mac.PlaywrightSharpTest/packages/PlaywrightSharp.0.162.0/build/netstandard2.0/../../runtimes/win-x64/native/PrintDeps.exe
```

There are some open issues, which I subscribed to, https://github.com/xamarin/xamarin-macios/issues/5265, and https://github.com/mono/mono/issues/15569.

One solution that worked for me was:
 * Migrate to `PackageReferences`.
    * Add `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`
    * Remove package.config
    * Re-add nuget packages

 * Add the following entries as mentioned on https://github.com/xamarin/xamarin-macios/issues/5265
```
<RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
<NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier>
```

**Comment by nor0x** [comment]
thanks for investigating @kblok.

i'm using `PackageReference` for my macOS csproj and have added `RuntimeIdentifiers` and `NugetRuntimeIdentifier`. But still get the exception. During build it seems to copy the correct files now, but only to the bin directory and not the .app bundle.

 ```
   Copying file from "/Users/johnny/.nuget/packages/playwrightsharp/0.162.0/runtimes/osx/native/ffmpeg-mac" to "/Users/johnny/test/MyApp.MacOS/bin/Debug/ffmpeg-mac".
    Copying file from "/Users/johnny/.nuget/packages/playwrightsharp/0.162.0/runtimes/osx/native/browsers.json" to "/Users/johnny/test/MyApp.MacOS/bin/Debug/browsers.json".
    Copying file from "/Users/johnny/.nuget/packages/playwrightsharp/0.162.0/runtimes/osx/native/ffmpeg.COPYING.GPLv3" to "/Users/johnny/test/MyApp.MacOS/bin/Debug/ffmpeg.COPYING.GPLv3".
    Copying file from "/Users/johnny/.nuget/packages/playwrightsharp/0.162.0/runtimes/osx/native/playwright-cli" to "/Users/johnny/test/MyApp.MacOS/bin/Debug/playwright-cli".
```

in your test, did the files get copied to the .app (MonoBundle) directory correctly?

**Comment by kblok** [comment]
You're right @nor0x

**Comment by kblok** [comment]
Could you tell me if this would work @nor0x? If it does I'll include a target for Xamarin.Mac

```
<ItemGroup>
    <PackageReference Include="PlaywrightSharp" GeneratePathProperty="true">
        <Version>0.162.0</Version>
    </PackageReference>
</ItemGroup>
<Target Name="CopyPlaywrightDriversToMonoBundle" AfterTargets="CopyFilesToOutputDirectory" Condition="$(TargetFrameworkIdentifier) == 'Xamarin.Mac'">
    <Message Text="Copy drivers to bundle" />
    <CreateItem Include="$(PkgPlaywrightSharp)\runtimes\osx\native\*.*">
        <Output TaskParameter="Include" ItemName="PlaywrightDriverFiles" />
    </CreateItem>
    <Copy SourceFiles="@(PlaywrightDriverFiles)" DestinationFolder="$(AppBundleDir)/Contents/MonoBundle/" />
</Target>
```

You might need to add the `GeneratePathProperty="true"` in the package.

**Comment by nor0x** [comment]
thanks for your fast replies @kblok, it's really helping me here. Unfortunately no success so far. 

I have added the `CopyPlaywrightDriversToMonoBundle` target to the csproj but something seems to be wrong with `$(PkgPlaywrightSharp)`, if i add it to the `<Message` tag for testing but no path gets printed to the build output and not playwright files end up in the final bundle at `$(AppBundleDir)/Contents/MonoBundle`

**Comment by kblok** [comment]
@nor0x did you add the GeneratePathProperty to the package?

```
 <PackageReference Include="PlaywrightSharp" GeneratePathProperty="true">
```

**Comment by nor0x** [comment]
@kblok yes `GeneratePathProperty` is in the `PackageReference`. The Playwright NuGet is referenced in a .netstandard project which is then referenced by my Xamarin.Mac app, does this make a difference?

**Comment by kblok** [comment]
Maybe you can try adding the package also to the Xamarin.Mac app?

This is my working project, just for reference.

[Xamarin.Mac.PlaywrightSharpTest.txt](https://github.com/microsoft/playwright-sharp/files/5624244/Xamarin.Mac.PlaywrightSharpTest.txt)

**Comment by kblok** [comment]
Adding that in the netstandard project would also be a nice test. We have a condition target there.

**Comment by nor0x** [comment]
i have tried added it to the cspoj of the Xamarin.Mac app - same error. I have also added the following test messages from your csproj

    ```
<Target Name="TestOutput" AfterTargets="CopyFilesToOutputDirectory">
        <Message Text="$([MSBuild]::IsOSPlatform('OSX'))" />
        <Message Text="$([MSBuild]::IsOSPlatform('MacOSX'))" />
        <Message Text="$(Platform)" />
        <Message Text="$(TargetFrameworkIdentifier.Contains('Xamarin.Mac'))" />
        <Message Text="$(TargetFrameworkIdentifier)" />
    </Target>
```

which gives me the following output:

```
Target TestOutput:
  Task "Message"
    True
  Done executing task "Message".
  Task "Message"
    False
  Done executing task "Message".
  Task "Message"
    x86
  Done executing task "Message".
  Task "Message"
    True
  Done executing task "Message".
  Task "Message"
    Xamarin.Mac
  Done executing task "Message".
```

i also couldn't get it working if it's in the netstandard project - for now i would be happy if it's working in the Xamarin.Mac csproj.

**Comment by kblok** [comment]
Could you share your csproj with the edits?

**Comment by nor0x** [comment]
sure thing, can i send it to you via email?

**Comment by kblok** [comment]
@nor0x sure!

**Comment by nor0x** [comment]
thanks @kblok - email is out

**Comment by kblok** [comment]
@nor0x and official v0.162.1 is on the way.

**Comment by nor0x** [comment]
Hey @kblok, unfortunately i have to comment in here again 🤷‍♂️

i am experiencing the following issue:
```
PlaywrightSharp.PlaywrightSharpException: No executable path is specified. Pass "executablePath" option directly.
Note: pass `debug: "pw:api"` to LaunchAsync to capture Playwright logs.
  at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T] (System.String guid, System.String method, System.Object args, System.Boolean ignoreNullValues, System.Text.Json.JsonSerializerOptions serializerOptions, System.Boolean treatErrorPropertyAsError) [0x001cf] in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:144 
  at PlaywrightSharp.BrowserType.LaunchAsync (PlaywrightSharp.LaunchOptions options) [0x0006b] in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/BrowserType.cs:102 
  at MyProject.BrowserManager.SetupBrowserAsync (System.String browserType) [0x0020d] in /Users/johnny/TestProject/BrowserManager.cs:44 
```

I have recently updated to `v0.162.1` where everything was working fine - and i haven't changed my code since. The only things i did was cleaning the local `~/.nuget` directory in ~ and installing the latest macOS update `11.1 (20C69)`. 

I'm happy to provide more info, isn't i strange that `/Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:144 ` appears in the stacktrace.

Thank you!

**Comment by kblok** [comment]
I believe it's because of the `~/.nuget` task you did.
How are you planning to make the Xamarin.Mac app to install the browsers. Are you calling InstallAsync?

**Comment by nor0x** [comment]
in the most recent version of my code i'm just using `await PlayWright.CreateAsync();` which was working because the browsers where downloaded before in `~/.nuget`.

I will try adding `InstallAsync` before `CreateAsync`. I thougt by restoring the packages and building the application it should work because in `~/.nuget/playwrightsharp/0.162.1/` there is a `runtimes` directory with the required pieces

**Comment by nor0x** [comment]
i have updated my code and added await `Playwright.InstallAsync()` before calling `Playwright.CreateAsync()`, but i'm getting the same error as before

**Comment by kblok** [comment]
The playwright cache keeps track of the directories using a browser version. If that directory is removed, and there are no more directories using that version, that browser version will be removed.

In local builds, we are using the place where the packages are stored (maybe we can improve that in the future). And that works for the main use case: UI testing.

Besides all that. You will need to call InstallAsync in your app, because your app clients won't have the browsers installed.

>i have updated my code and added await Playwright.InstallAsync() before calling Playwright.CreateAsync(), but i'm getting the same error as before

I'll take a look

**Comment by nor0x** [comment]
i have some more info as i'm trying to understand what could have gone wrong in my case. I now did a fresh install of the playwright-sharp-tool to see if i can install the browsers via the tool. This leads to the following error:

```
Unhandled exception. System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at PlaywrightSharp.Transport.Connection.InstallAsync(String driverPath, String browsersPath) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 92
   at PlaywrightSharpTool.Program.<>c.<<Main>b__0_0>d.MoveNext() in /home/runner/work/playwright-sharp/playwright-sharp/src/tools/PlaywrightSharpTool/Program.cs:line 14
--- End of stack trace from previous location where exception was thrown ---
   at PlaywrightSharpTool.Program.<Main>(String[] args)
zsh: abort      playwright-sharp install-browsers
```

**Comment by kblok** [comment]
Hey @nor0x, sorry for the late response. But your issues was on my to-do list :)
I got your error using v0.160.2 but it worked on v0.170.2
This was my test:
 * Delete ~/Library/Caches/ms-playwright.
 * Run the Xamarin.Mac app.
 * Expect the browser to be downloaded there.
 * Launch a browser and get the version.

If it doesn't work, would you mind creating another issue?

**Comment by nor0x** [comment]
0.170.2 works great in my first tests. If any errors related with my previous tests occur, i will create a new issue.

Thanks @kblok !
