### ISSUE TITLE
Docker Container without the need to download the browsers

### ISSUE THREAD

**Issue by kurtisane** [microsoft/playwright-sharp#1019]
Hi,
I'm building a .Net Core 3.1 Web Api contained in a Docker Container. I found a different issue here that already "explained" how to do so. 

I would just like to know which Docker Tag corresponds to the current nuget lib (0.152.0) without the need to download the browsers when running InstallAsync. 

My actual goal is to not run InstallAsync at all and have all the files already there. 

Regards!

**Comment by kblok** [comment]
Can you test with this recipe https://github.com/microsoft/playwright-sharp/issues/982#issuecomment-720690149 using the `v1.5.2` tag?

**Comment by kurtisane** [comment]
Thanks that did it for me !
