### ISSUE TITLE
Websocket property in WebSocketEventArgs should probably be public?

### ISSUE THREAD

**Issue by javiercn** [microsoft/playwright-sharp#1034]
I was trying to use page.Websocket with 1.162.0 and it seems it's not possible since the property is marked as internal. I believe this was just an oversight and should be public instead.

https://github.com/microsoft/playwright-sharp/blob/5b0ad490548016bf2d7e4da8efec5a8600236ff6/src/PlaywrightSharp/WebSocketEventArgs.cs#L13

**Comment by kblok** [comment]
Ops. You are right @javiercn

**Comment by javiercn** [comment]
I can wait until 1.170.0 no problem.
