### ISSUE TITLE
0.162.1 Driver not found

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#1035]
Hi Dario,

0.152.0 has been working really great here on multiple platforms, so thanks again for bringing us this excellent tool !!

When upgrading to 0.162.1 in OSX we get the message (Driver not found neither at .../bin/Debug/runtimes/osx/native/playwright-cli', nor .../bin/Debug/playwright-cli') when running InstallAsync.

It's the same error as mentioned in the Big Sur issue closed recently but we tested Catalina with target framework net48.
On Windows the issue does exist, Ubuntu not yet tested.

Did we miss some new location configuration setting ?

Thanks,
-M

**Comment by kblok** [comment]
Hey!
Why don’t you use net core?

**Comment by kababoom** [comment]
Because of legacy stuff in our framework we are not ready to completely switch to core.

**Comment by kblok** [comment]
@kababoom can you create a project I can test?

**Comment by kababoom** [comment]
It's just a net48 console app but sure. Little busy now so probably Monday ...😊

**Comment by kababoom** [comment]
Took me some time but can confirm this works perfect....

Thank you 😊
