### ISSUE TITLE
EvaluateAsync Esprima parsing fails on >ECMA 2016 

### ISSUE THREAD

**Issue by nh43de** [microsoft/playwright-sharp#1039]
**Some Background:** Puppeteer-sharp has two functions for evaluating JS, namely "evaluate function" and "evaluate expression", Playwright consolidated these into a single API, "EvaluateAsync", and uses [Esprima-dotnet](https://github.com/sebastienros/esprima-dotnet) to parse that function and determine whether it's a function or expression before sending to Chromium. Which is cool. But,

The **problem** is that Esprima-dotnet doesn't seem to support ECMA Script >2016, so when calling .EvaluateAsync() on an ECMA 2020 that say, uses option chaining e.g. var name = person?.firstName, the C# method throws a parsing exception and does not send to the underlying browser.

Some **solutions**: a) provide a fallback when Esprima parsing fails, e.g. maybe default fallback to function since this is an easy convention to remember b) pass a boolean / options object for the evaluation that would allow the user to disable Esprima parsing and/or specify whether it's an expression or a function c) Update / replace Esprima .NET to support latest ECMA Script. Easier said than done obviously but these are options.

Current **workarounds**: escape js string and use eval()

Just my thoughts, and happy to submit a PR if someone can point me in the right direction. Thanks for looking.

**Comment by kblok** [comment]
Hey, @nh43de could you tell me a little bit more about your use case?
Are you importing scripts from other places? Because my first thought would be why no writing ECMA 2016.

**Comment by nh43de** [comment]
Nothing fancy, just using nice new ECMA script features like optional chaining (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which saves me from having to write tedious code. 

Surprised that more people aren’t having this problem. 

To me it just seems silly to have the method rely on the parsing to succeed by some secondary parsing layer. I get the convenience aspect that it brings but it shouldn’t throw an error because the outdated ECMA 2016 parser fails to recognize new language features that the web engine it’s passing it along to certainly can.

**Comment by kblok** [comment]
@nh43de I can review a PR with a bullet-proof way of detecting if a string contains a function or an expression and supporting new ECMA Scripts.

**Comment by nh43de** [comment]
@kblok a preferred approach would be much simpler:
- Parse using Esprima as before
  - If parsing succeeds, continue as before
  - If parsing fails
    - Instead of throwing an unhandled parsing exception, pass as a function string

That way, it becomes a matter of convention: just pass wrapped in a function. That is, until the Esprima engine can catch up beyond ECMA 2016.

**Comment by nh43de** [comment]
> @kblok a preferred approach would be much simpler:
> 
> * Parse using Esprima as before
>   
>   * If parsing succeeds, continue as before
>   * If parsing fails
>     
>     * Instead of throwing an unhandled parsing exception, pass as a function string
> 
> That way, it becomes a matter of convention: just pass wrapped in a function (when parsing fails). That is, until the Esprima engine can catch up beyond ECMA 2016. Unless I am missing something.

@kblok or anyone else, thoughts on this approach?

**Comment by kblok** [comment]
> Instead of throwing an unhandled parsing exception, pass as a function string

I think we could do this. If the script is invalid we will end up with an exception from the driver. We will ship this for v0.190.0

**Comment by kblok** [comment]
@nh43de I hit a wall upstream. The driver is validating the script and the Node version is not ECMA 2020 compatible yet. So, although I think this is a valid approach, you won't be able to implement your code yet. I suggest you create an issue upstream.

**Comment by lahma** [comment]
Commenting on closed issue, but latest Esprima 2 beta has support for also optional chaining https://github.com/sebastienros/esprima-dotnet/releases/tag/v2.0.0-beta-1339 .

**Comment by pavelfeldman** [comment]
Esprima dependency and function detection logic has been removed!
