### ISSUE TITLE
MouseDown and MouseUp with Coordinates

### ISSUE THREAD

**Issue by nor0x** [microsoft/playwright-sharp#1041]
Hey!  it's me again 👋
i was wondering if there is a way to use `IPage.Mouse.DownAsync` or `IPage.Mouse.UpAsync` with coordinates?
i'm trying to perform text selection (mouse movement while the left mouse button is pressed) with Playwright-Sharp, and therefore it seems necessary to have something like:

```cs
Mouse.DownAsync(10, 10);
Mouse.MoveAsync(15, 35);
//UpAsync wouldn't need x | y in this case
Mouse.UpAsync(15, 35);
```

it's a similar flow to the DragAndDropTests without a specific element but with coordinates
https://github.com/microsoft/playwright-sharp/blob/ac2cc6e95e9a81c918366fa38877e3e7b0aa8682/src/PlaywrightSharp.Tests/Mouse/DragAndDropTests.cs#L30

Is this something that's planned for Playwright(Sharp)?

Thank you

**Comment by kblok** [comment]
This won't work?

```
await page.Mouse.MoveAsync(10, 10);
await page.Mouse.DownAsync();
await page.Mouse.MoveAsync(15, 35);
await page.Mouse.UpAsync();
```

**Comment by nor0x** [comment]
that was easy! thanks @kblok your solution was working just fine
