### ISSUE TITLE
Documentation link is not working

### ISSUE THREAD

**Issue by josemedina760** [microsoft/playwright-sharp#1042]
Getting a 404 when I try to access the .NET documentation in the README.

URL: https://playwrightsharp.dev/api/index.html

Where is the .net API reference stored at ?

![image](https://user-images.githubusercontent.com/12689117/101535241-36d31400-394d-11eb-9cf5-300514133a6b.png)

**Comment by kblok** [comment]
Something got missing. Not it's working, but I think this should be the right link https://playwrightsharp.dev/api/PlaywrightSharp.html

**Comment by josemedina760** [comment]
Thank you sir.
