### ISSUE TITLE
Runtime driver downloading

### ISSUE THREAD

**Issue by KoalaBear84** [microsoft/playwright-sharp#1045]
Today started to implement a PDF generator based on an URL.

Then I noticed PuppeteerSharp was kind of 'replaced' by Playwright, we sounds like no problem at first. But then I noticed it doesn't work without the "runtimes" subfolder.

This is where the problem starts, we can only supply the PDF generator as a DLL, no subfolders. So it will not work.

So I have to choose between two 'evils'. PuppeteerSharp which will die, and Playwright which I can't use :)

It's like #988 but then runtime.

Any solution to this?

**Comment by kblok** [comment]
Hey @KoalaBear84, Playwright doesn't replace anything. They are two similar tools with different scopes and focused on different use cases.

Why can't you support the runtimes folder?

**Comment by KoalaBear84** [comment]
Thanks for your fast response. OK, that was not fully clear to me, mainly because it logically got quieter on the PuppeteerSharp repo :)

It's a SaaS solution we are deploying it to, it has no like (S)FTP deployment options. You can only upload a .ZIP and it will only use/unpack a DLL in it. So we are limited by that.

**Comment by kblok** [comment]
I'm the author of PuppeteerSharp and PlaywrightSharp. I'm now a third-party contributor to the PlaywrightSharp.

What the Playwright team would say (these are my words not them) is that Playwright is a "Testing library". They will be willing to support different scenarios but always around that use case: Testing.
What is inside the runtimes folder is the Playwright driver. So I don't think there would be a refactor around that if it's not for testing purposes.

**Comment by KoalaBear84** [comment]
OK, thanks. I'll switch back to PuppeteerSharp.

Already found a good way to use a newer Chromium version with a newer Revision. Sadly not a perfect match in http://omahaproxy.appspot.com/ which currently is 812852 for stable, but that one doesn't exist on https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/

Is there a better method? Sorry that this maybe isn't related to this project.

**Comment by kblok** [comment]
I would move this conversation to the other project.

**Comment by KoalaBear84** [comment]
Thanks, closed to continue on new issue on PuppeteerSharp.
