### ISSUE TITLE
Screenshot question

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#1047]
Hi Dario,

Using Headful Chromium on Ubuntu with `page.ScreenshotAsync(true)` I occasionally get: (Cannot take screenshot while page is navigating) or: One or more errors occurred. (Timeout 30000 exceeded) 

To me this indicates the browser is locked up in a navigation or loading session and is unresponsive right? 
(while writing this thinking this might be because we use the full-page option and the resizing cannot take place? will check this)...

Is there any way we can work around this? we would like to get a screenshot somehow..

Many thanks,
-M

**Comment by kblok** [comment]
Hey @kababoom can you create some example I can reproduce?

**Comment by kababoom** [comment]
Thanks @kblok, of course it only happens on a test I cannot share. Let me see if I can create something.

What are your thoughts on the above mentioned errors?

 Thanks,
-M

**Comment by kababoom** [comment]
It's still happening occasionally but conclusion for now is that this is browser/site related.

Thanks,
-M
