### ISSUE TITLE
Response not getting right status code

### ISSUE THREAD

**Issue by jordanspangenberg** [microsoft/playwright-sharp#1057]
I was getting unexpected results for `response.Ok` and when I debugged I see Ok == false and am not sure why. The request is returning `201 Created` so that should be good. I see `Status == Created` and `StatusText == "Created"` so I'm wondering if something is wrong here.
![image](https://user-images.githubusercontent.com/32577210/102423096-147c6e80-3fbd-11eb-9f0b-54c4e09043ea.png)

**Comment by kblok** [comment]
Good catch!
We'll get that fixed in the upcoming version.
