### ISSUE TITLE
Response.Status returns HttpStatusCode instead of int

### ISSUE THREAD

**Issue by jordanspangenberg** [microsoft/playwright-sharp#1065]
In the JS docs Response.Status returns a number. [link](https://playwright.dev/docs/api/class-response#responsestatus)

In Playwright-sharp it returns HttpsStatusCode. So you can't do `Assert.True(response.Status == 200)` because of the type difference.

**Comment by kblok** [comment]
You can do `Assert.True(response.Status == HttpStatusCode.Ok)` or `Assert.True((int)response.Status == 200)`

**Comment by jordanspangenberg** [comment]
That works too! Thanks
