### ISSUE TITLE
How to set browser position?

### ISSUE THREAD

**Issue by ScottHuangZL** [microsoft/playwright-sharp#1068]
**First of all, thanks for your great job of create playwright-sharp, I like it:)**

As you know we can set browser size through: page.SetViewportSizeAsync
Or before when I use chromium driver, I can use driver.set_window_position(1000, 0) to meet my requirement.

**However, in paywright-sharp, I did not find out a way to change browser position, _can you advise of it?_**

I go to DOC https://playwrightsharp.dev/documentation/index.html  to try search answer, but did not find it.
**Another proposal is enhance DOC index** or hierarchy for user to easy search samples.  
Take download as example, it did not show in "basic sample" session, when I search API download, it also did not show the sample, I finally find download sample "https://playwrightsharp.dev/documentation/Page.Download.html?q=download" after search issues in this github. 

Should the DOC web have a better index for user to easily follow if you already prepare contents? thanks.

**Comment by kblok** [comment]
Hey @ScottHuangZL, why do you need to set the window position?
do you want to create a specific issue for the docs?

**Comment by ScottHuangZL** [comment]
> Hey @ScottHuangZL, why do you need to set the window position?
> do you want to create a specific issue for the docs?

I usually use headless, then no need set browser location.

However, sometimes, especially at debug/development/demo period, I want put the console log output window at left, and browser web UI window at right when I tentative turn off headless (mean show web UI).  So I need a way to move the browser to right or left, anyway just make the log & web window side by side.

I usually add a auto screen capture function in case encounter any playwright automation exception.  That means my program will capture the full screen both for the log text and web UI contents and save to folder for double check later.

Hope this make sense to you.

Regards,
Scott Huang

**Comment by ScottHuangZL** [comment]
> do you want to create a specific issue for the docs?

Please show more "how to" samples in your documentation **homepage**, may be left pane.

**Comment by kblok** [comment]
> Please show more "how to" samples in your documentation homepage, may be left pane.
Yeah! do you want to create an issue with that?

**Comment by ScottHuangZL** [comment]
I have send 2 pull requests. You have accept first 1 already.

Another is https://github.com/microsoft/playwright-sharp/pull/1071 
Which is some tips to adjust some common settings when I try playwrights in past 2 days, I believe it is helpful to other people.

I will add it into side page after you accept 2nd pull. 

Btw, can you advise how to adjust browser position? Thank.s

**Comment by kblok** [comment]
Sorry for the delay @ScottHuangZL. There is no method in PlaywrightSharp to set the window position. But if you are using chromium you can use pass the [window-position](https://peter.sh/experiments/chromium-command-line-switches/#window-position) command-line argument in the `args` argument when you call `LaunchAsync`.

**Comment by ScottHuangZL** [comment]
Thanks for the advisement.
