### ISSUE TITLE
playwright-sharp CLI tool does not recognize .NET 5 SDK

### ISSUE THREAD

**Issue by cpeth** [microsoft/playwright-sharp#1077]
After installing the CLI tool in a Linux docker container that has .NET 5 SDK installed, attempting to run the tool gives the following response:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64
```

**Comment by kblok** [comment]
We are trying to kill the global tool. What are you using it for?

**Comment by cpeth** [comment]
Oh I see now.  Since there wasn't a link to the preferred Nuget package in the readme, I simply searched for Playwright on NuGet Gallery and ended up with the global tool.  Perhaps a link or installation instructions could be added to the readme?  I can create a PR if that would help.

**Comment by kblok** [comment]
We explain most scenarios here https://github.com/microsoft/playwright-sharp/blame/master/README.md#L37
What do you think about that?

**Comment by cpeth** [comment]
That section is great, I missed the NuGet link/badge in the H1 header.
