### ISSUE TITLE
IgnoredDefaultArgs not working

### ISSUE THREAD

**Issue by tunvit** [microsoft/playwright-sharp#1080]
I was used IgnoredDefaultArgs to remove some chromium default args but it not working. 

` LaunchPersistentOptions option = new LaunchPersistentOptions();`
  `          option.IgnoredDefaultArgs = new string[] { "--enable-automation", "--disable-extensions" };`
         `    option.Headless = false;`
        `     option.ExecutablePath = _execPath;`
          `  _player = await Playwright.CreateAsync();`
            ` _context = await _player.Chromium.LaunchPersistentContextAsync(_userDataDir, option);`

Log

> <launching> D:/../chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage **--disable-extensions** --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run **--enable-automation** --password-store=basic --use-mock-keychain --user-data-dir=D:/../Tmp/4e4d6c332b6fe62a63afe56171fd3725 --remote-debugging-pipe --no-sandbox about:blank
> <launched>

Any idea how to fix this?
Thank you!

**Comment by kblok** [comment]
Found the issue @tunvit. Good Catch!
