### ISSUE TITLE
LaunchOptions.FirefoxUserPrefs not working with existing firefox profile

### ISSUE THREAD

**Issue by tunvit** [microsoft/playwright-sharp#1085]
Hello! FirefoxUserPrefs not working with existing firefox profile, please check, thank you!
**Not working**
`LaunchOptions option = new LaunchOptions();`
`option.FirefoxUserPrefs = new Dictionary<string, object>() { { "media.peerconnection.enabled", false } }; `
`var browserContext = _player.Firefox.LaunchPersistentContextAsync(_userDataDir, option);`

![Screenshot_5](https://user-images.githubusercontent.com/3454790/103463255-b8a43a80-4d5d-11eb-95db-651ae10c5bcd.png)

**Work ok**

`LaunchOptions option = new LaunchOptions();`
`option.FirefoxUserPrefs = new Dictionary<string, object>() { { "media.peerconnection.enabled", false } }; `
`var browser = _player.Firefox.LaunchAsync(option);`

![Screenshot_6](https://user-images.githubusercontent.com/3454790/103463257-bb9f2b00-4d5d-11eb-8e3d-2ed64d2e7b37.png)

**Comment by kababoom** [comment]
Working for me, I think you need to replace LaunchOptions with LaunchPersistentOptions..
launchPersistentOptions = new LaunchPersistentOptions();

-M

**Comment by kblok** [comment]
Hey @tunvit, Thanks for the report. FirefoxUserPrefs is not supported on LaunchPersistentAsync. It's not part of the API in Playwright, so I'm removing it. You can read a conversation about that here https://github.com/microsoft/playwright/pull/4136 .
