### ISSUE TITLE
Missing BrowserContext.IsClosed() ?

### ISSUE THREAD

**Issue by Joe118** [microsoft/playwright-sharp#1089]
I noticed there is a Page.IsClosed() but no BrowserContext.IsClosed()

Two questions:

* Is this intentional? If so, what is the reason? There *is* a BrowserContext.CloseAsync...
* How can I check if a browser context is still valid?

Thanks, --Joe Finn

**Comment by kblok** [comment]
What do you think about this @pavelfeldman ?

**Comment by Joe118** [comment]
The code already has a boolean IsClosedOrClosing internal variable. The BrowserIsClosed() method could just expose the value,,,

**Comment by kblok** [comment]
@Joe118 yeah, we have the value. But all language bindings should share the same API.

**Comment by kblok** [comment]
Related to https://github.com/microsoft/playwright/issues/5230. Please step in there if you want this to be implemented.
