### ISSUE TITLE
New release with Playwright driver v1.7.1?

### ISSUE THREAD

**Issue by xyfoo** [microsoft/playwright-sharp#1090]
There was 2 selector regression bug found in the v0.170.2 (with v1.7.0 drivers), and are fixed in the [v1.7.1](https://github.com/microsoft/playwright/releases/tag/v1.7.1) drivers.

I can workaround by downgrading it to v0.162.1, but is there any planned release that will use the latest driver?

Thanks,
Frankie

**Comment by kblok** [comment]
We can ship a new version @xyfoo!

**Comment by xyfoo** [comment]
That's great!
