### ISSUE TITLE
PlaywrightSharp.PlaywrightSharpException: 'ignoreDefaultArgs: expected array, got boolean'

### ISSUE THREAD

**Issue by Samclay8** [microsoft/playwright-sharp#1091]
await using var browser = await playwright.Chromium.LaunchPersistentContextAsync(headless: false, ignoreHTTPSErrors: true, args: arg, userDataDir: @"C:\Users\user\source\repos\OutlookForwarder", executablePath: @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", ignoredDefaultArgs: barg, ignoreDefaultArgs: true);

I'm not understanding why ignoreDefaultArgs: true is not being accepted.

**Comment by kblok** [comment]
I'll take a look at it. Thanks for the report!

**Comment by kblok** [comment]
It will be fixed on #1092 @Samclay8. You will get a breaking change in the next version.

**Comment by Samclay8** [comment]
> It will be fixed on #1092 @Samclay8. You will get a breaking change in the next version.

Perfect thank you. Great work on this project, it's been hugely beneficial already for our testing.
