### ISSUE TITLE
macOS notarization fails

### ISSUE THREAD

**Issue by nor0x** [microsoft/playwright-sharp#1093]
i'm using Playwright-Sharp in a macOS project which gets distributed to our customers. We use the apple notarization service to allow proper execution with gatekeeper enabled. Since i have added Playwright-Sharp to the project the notarization fails, because the added binaries are not properly signed and don't have the `hardened runtime` flag enabled. Here is a log of the apple notarization service:

```
{
  "logFormatVersion": 1,
  "jobId": "1234567890",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "MyApp.app.zip",
  "uploadDate": "2021-01-09T14:54:20Z",
  "sha256": "1234567890",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/playwright-cli",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/playwright-cli",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/playwright-cli",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/ffmpeg-mac",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/ffmpeg-mac",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/ffmpeg-mac",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
}
```

**Comment by kblok** [comment]
@nor0x would you mind moving this issue to https://github.com/microsoft/playwright-cli ?

**Comment by nor0x** [comment]
@kblok done! sorry didn't know this was the wrong place for the issue

**Comment by kblok** [comment]
No worries. It's just about getting the right eyes on the issue.

**Comment by nor0x** [comment]
hi @kblok 👋 unfortunately i have to follow up on this issue. I have updated my application to the latest version of `Playwright-Sharp` 0.180.0 which should include the cli, right?

Currently calling `await Playwright.CreateAsync();` results in the following error for me.

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/Users/johnny/Documents/dev/Deon/DeonX/Deon.Products.DeonX.MacOS/bin/Debug/Deon.app/Contents/MonoBundle/package/lib/cli/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


PS: i know this is not directly related with notarization, but therefore i keep an eye on the upstream where things like ffmpeg loading are happening 👍

**Comment by kblok** [comment]
Hey @nor0x, sorry for the headaches.
I think it might be related to this https://github.com/microsoft/playwright-sharp/issues/1145

**Comment by nor0x** [comment]
no worries, just wanted to make sure Playwright is stable 🙂
anything i can test or provide? I see there is already a repro in #1145

**Comment by kblok** [comment]
@nor0x nothing to test here. But I'll get here before 0.190.0.

**Comment by kblok** [comment]
@nor0x if you find a way for us to test your environment as we do here https://github.com/microsoft/playwright-sharp/blob/master/.github/workflows/nuget-package-tests.yml#L50, it would be awesome.
I hate breaking your code, but we don't currently have a way to check it.

**Comment by nor0x** [comment]
sorry @kblok i'm still trying to find a proper way to contribute tests that reflect the usecase i'm working on. Unfortunately it's a multi step process (Release -> Signing -> Notarization) where the notarization part is handled by apple itself and returns in an async way. I haven't found a way to test these steps locally - but i will keep investigating 💪

**Comment by kblok** [comment]
@nor0x at least the previous step. We build your project and we make sure that the drivers were properly copied.

**Comment by nor0x** [comment]
sorry for the delay, i have build a repro project with a test that currently just checks for the existence of `Contents/MonoBundle/package/lib/cli/cli.js` within the macOS .app file. Currently i assume that everything that should live in the package directory is in the first level directly in  `Contents/MonoBundle`.

Here is the project which consists of a Xamarin.Forms project a Xamarin.Mac project and an mstest project.
https://github.com/nor0x/playwright-xmac-test

this is a very similar project structure to the main application that i'm building which is closed source for now

**Comment by pavelfeldman** [comment]
I'm triaging the bugs in preparation to the stable release and it is unclear whether this issue is addressed or not. Could you verify it against https://www.nuget.org/packages/Microsoft.Playwright/1.11.1-alpha-2 and file a new issue in case this still is a problem?
