### ISSUE TITLE
BringToFrontAsync() not working with IBrowserContext

### ISSUE THREAD

**Issue by tunvit** [microsoft/playwright-sharp#1094]
Hello! `BringToFrontAsync` not working with `IBrowserContext`, please check, thank you!

**Work ok**
```
IChromiumBrowserContext chromeContext=...
//do something
await chromeContext.Pages[0].BringToFrontAsync();
```

**Not working**
```
IBrowserContext browserContext=...
//do something
await browserContext.Pages[0].BringToFrontAsync(); //nothing happened
```

**Comment by kblok** [comment]
Related to https://github.com/microsoft/playwright/issues/3570

**Comment by pavelfeldman** [comment]
That's highly unlikely, it is the same method... Closing it as a lot has changed since February. Please verify against https://www.nuget.org/packages/Microsoft.Playwright/1.11.1-alpha-2 and file in case this still is an issue!
