### ISSUE TITLE
Question on leftover files tmp

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#1107]
First of all thanks again for this great piece of work!!!

I do have question, after each session we have leftover files in /tmp starting with playwright_* 
After a few weeks this piles up and although I can easily clean them I'm wondering if this is intentionally?

Cheers,
-M

**Comment by kblok** [comment]
Hey @kababoom, I would move this issue to the Playwright repository.

**Comment by kababoom** [comment]
Sure......
