### ISSUE TITLE
Question: Production Readiness

### ISSUE THREAD

**Issue by KyleCrowley** [microsoft/playwright-sharp#1109]
(Apologies in advance if this is the wrong forum for this question)

First off, I'm a huge fan of [puppeteer-sharp](https://github.com/hardkoded/puppeteer-sharp). It's been a breeze using it to control Chromium (previously I was controlling Chromium via a TypeScript app w/ puppeteer, which was called from a C# app), so many thanks there.

My question: Is playwright-sharp "production ready"? I am assuming the answer is no judging by the latest version number, but I don't see a disclaimer indicating this library shouldn't be used in a production environment. I can continue to use puppeteer-sharp for the time being, but if more focus is going to be shifted towards playwright-sharp, I'd like to start making the switch ASAP.

**Comment by kblok** [comment]
Hey @KyleCrowley, PlaywrightSharp is production-ready. These are the main reasons why it's still v0:
 * This is a great opportunity to listen to user feedback and apply changes without thinking about backward compatibility.
 * We are working on better tooling so we can keep the API closer to Playwright's API easily. So we might change some API in other to be closer to Playwright.

All in all. It's production-ready, but expect to get some breaking change eventually. Go ahead! we are here to help :)

**Comment by KyleCrowley** [comment]
That's great to hear. Thanks for the speedy response!
