### ISSUE TITLE
RouteAsync redirect support

### ISSUE THREAD

**Issue by vandervillain** [microsoft/playwright-sharp#1146]
Trying to get Playwright Sharp working with OIDC integration tests. 
I have an authorization URL that the Page navigates to, and then when that server completes some process, it redirects to our callback URL with the access token as part of the querystring. However, we're in a client-side app, and the callback URL is a nonexistent endpoint that we intercept and then parse to grab the access token. 

I notice that this works in regular Playwright, it intercepts the callback that the auth page redirects to:

`    page.route('http://localhost:3000/signin-oidc*', async req => {
      req.abort()
      var token = await getAccessToken(req.url(), codeVerifier)
      return resolve(token)
    })`
    
   but this does not work in PlayWright Sharp. It does not intercept the redirect to localhost, and my page just goes to a "This site can't be reached" page (nothing running on localhost, intentionally). If I switch the route to '**' it catches the first request to the auth URL but not the redirect.
   `        await page.RouteAsync("http://localhost:3000/signin-oidc*", async (route, _) =>
            {
                // this code is never hit
                await route.AbortAsync();
                string token = await GetAccessToken(route.Request.Url, urlData.CodeVerifier);
                promise.TrySetResult(token);
            });`
  
Not sure if this is actually an issue, or by design?

**Comment by kblok** [comment]
@vandervillain can you help me with some test I can run locally?
Our tests are able to cook redirect and everything we need to test your scenario.
https://github.com/microsoft/playwright-sharp/blob/master/src/PlaywrightSharp.Tests/RequestInterception/PageRouteTests.cs#L97

**Comment by pavelfeldman** [comment]
Looks like a bug in glob matcher?

**Comment by pavelfeldman** [comment]
You should do `http://localhost:3000/signin-oidc/*`, the bug is in the JS version.

**Comment by pavelfeldman** [comment]
Looks like it has been resolved due to no reply since Feb 15th. Closing.
