### ISSUE TITLE
Test monobundle as part of the nuget tests

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#1181]
sorry for the delay, i have build a repro project with a test that currently just checks for the existence of `Contents/MonoBundle/package/lib/cli/cli.js` within the macOS .app file. Currently i assume that everything that should live in the package directory is in the first level directly in  `Contents/MonoBundle`.

Here is the project which consists of a Xamarin.Forms project a Xamarin.Mac project and an mstest project.
https://github.com/nor0x/playwright-xmac-test

this is a very similar project structure to the main application that i'm building which is closed source for now

_Originally posted by @nor0x in https://github.com/microsoft/playwright-sharp/issues/1093#issuecomment-786567662_

**Comment by nor0x** [comment]
follow-up to this issue - currently i'm experimenting with the version `0.192.0` which creates a folder named `@(PlaywrightDriverFiles->;'bin` in my macOS project directory, which contains an `.app` folder with `Contents` and `MonoBundle` which is empty though
![image](https://user-images.githubusercontent.com/3210391/111435467-1d3a2900-8701-11eb-9424-f99d8db8d9e0.png)

![image](https://user-images.githubusercontent.com/3210391/111435208-c5032700-8700-11eb-86dc-3df58e3387fa.png)

**Comment by nor0x** [comment]
workaround for every who has issues with the `.playwright` directory inside the `MonoBundle` in the `.app` folder. I have added this custom target to my macOS project file which copies everything from the `bin/{configuration}/.playwright/osx` folder into `Contents/MonoBundle/`

```
<Target Name="CopyPlaywrightMacOS" AfterTargets="CopyFilesToOutputDirectory">
    <ItemGroup>
        <OutFiles Include="$(TargetDir)\.playwright\osx\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(OutFiles)" DestinationFolder="$(TargetDir)\Deon.app\Contents\MonoBundle\.playwright\osx\%(RecursiveDir)" />
</Target>
```

**Comment by kblok** [comment]
Don't you wan to take a look at it https://github.com/microsoft/playwright-sharp/blob/main/src/PlaywrightSharp/build/netstandard2.0/PlaywrightSharp.targets#L23 ?

I remember doing that and testing it... :/

**Comment by nor0x** [comment]
i did take a look at it and it seems that the path in `DestinationFiles` here is wrong: 
https://github.com/kblok/playwright-sharp/blob/2caf57a7d005596abb7857fb7085b08a66aa002b/src/PlaywrightSharp/build/netstandard2.0/PlaywrightSharp.targets#L30

any specific reason why we have `PlaywrightDriverFiles->` in `DestinationFiles="...` i think this gets interpreted wrong on macOS

**Comment by kblok** [comment]
@nor0x I think we have an extra semi-colon there...

**Comment by nor0x** [comment]
@kblok you are right - at first i thought it's part of the copy command 👀
