### ISSUE TITLE
SnapshotAsync should return an object not a string

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#1185]
https://github.com/microsoft/playwright-sharp/pull/1113/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.csproj&file-filters%5B%5D=.xml#diff-a6945f2731fe711ebb9a0ad88372efe18ed6a706d9401a180811a4e0c4e83d1aR89

**Comment by avodovnik** [comment]
Actually, this is intentional. It was decided that the `Accessibility` object provides no added value to the caller so we'd rather return a `string`.
