### ISSUE TITLE
Review timeout arguments

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#1200]
They should be `int? timeout = null`

https://github.com/microsoft/playwright-sharp/pull/1113/files#diff-a8d5f823294cea4f75ff4d733c99b11f61e5ce4aa4bd98b186da9adc83141101R131

**Comment by cirrusone** [comment]
Would it be more intuative to have `Timespan?` instead of `int?` for timeout args? I keep forgetting if it's seconds or milliseconds when it's just `int? timeout = null`.

**Comment by kblok** [comment]
What do you think about that @avodovnik ?

**Comment by avodovnik** [comment]
We've talked a lot about this, if you remember @kblok. Especially in the context of using language specific types, like `Timespan` and `FileInfo`, etc. That said, I do think, genuinely, `Timespan` would be a very handy one here. 

When we're nearly done with the alpha, let's see if we can squeeze this one in, how's that? I want to make sure we don't introduce additional (major) breaking changes after the alpha.
