### ISSUE TITLE
macos error

### ISSUE THREAD

**Issue by coffice12** [microsoft/playwright-sharp#1223]
EXEC : error : Lock file is already being held
/Users/cafe/.nuget/packages/playwrightsharp/0.191.1/build/netstandard2.0/PlaywrightSharp.targets(19,5): error MSB3073: 命令“./playwright.sh install”已退出，代码为 1。
    21 个警告
    2 个错误

**Comment by coffice12** [comment]
demo code:

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.bing.com");
await page.ScreenshotAsync(path: outputFile)

**Comment by kblok** [comment]
Your code worked for me. Maybe it's something temporal? can you try to build again?

**Comment by coffice12** [comment]
Environment.SetEnvironmentVariable("PWDEBUG", "1");
            Console.WriteLine("Environment："+ Environment.GetEnvironmentVariable("PWDEBUG"));
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new LaunchOptions { Headless = false, Devtools=true,Timeout=0, ExecutablePath = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
            
            
            
            ok。must set ExecutablePath。

**Comment by coffice12** [comment]
but Another problem arises：Devtools=true

browser  not show debug windwos

**Comment by pavelfeldman** [comment]
Please verify with https://www.nuget.org/packages/Microsoft.Playwright/1.11.1-alpha-2 and re-open or file new issue in case there still is a problem!
