### ISSUE TITLE
Referencing playwright in base project fails: Driver not found in any of the locations

### ISSUE THREAD

**Issue by andyTheCoder** [microsoft/playwright-sharp#1224]
**Context:**
- GOOD Playwright Version: 0.170.2
- BAD Playwright Version: all later
- Operating System: Windows

**Code Snippet**
* https://github.com/andyTheCoder/playwright-parent
* run test in child project: fails

**Describe the bug**
1. Base project contains playwright nuget reference
2. Child project references base project
3. Child project does not contain playwright nuget reference
4. Test running in child project fails with: PlaywrightSharp.PlaywrightSharpException, Driver not found in any of the locations.

Note that when the child project includes the playwright nuget package, all is ok

**Comment by kblok** [comment]
@andyTheCoder as we are copying the drivers using build targets, you need to reference PlaywrightSharp in the output project. 
We could improve that, but at the moment that should be considered a prerequisite.

**Comment by andyTheCoder** [comment]
Thanks for the quick response.
This is not a showstopper, it is just not expected behaviour of project references.
NB the reason I tagged this issue with regression is because the expected behaviour was working in version: 0.170.2

**Comment by pavelfeldman** [comment]
I believe this has been resolved in https://www.nuget.org/packages/Microsoft.Playwright/1.11.1-alpha-2. Please file a new issue if this still happens.

**Comment by andyTheCoder** [comment]
I can confirm that this has been resolved. Tested in Microsoft.Playwright Version="1.12.2"
