### ISSUE TITLE
Wrong platform path on linux

### ISSUE THREAD

**Issue by codernr** [microsoft/playwright-sharp#1225]
In [`Connection.GetPath`](https://github.com/microsoft/playwright-sharp/commit/3709d37ab2badc7745d2fadc1ce7806e141702e8#diff-aa742ca6795086e6cf2d22214db0560a0811ad24a7f22ee148c198a9d47b7849R294) `linux` is used when constructing driver path, but the driver can be found in `unix` folder so it doesn't find `playwright.sh`.

**Comment by kblok** [comment]
Ops. I bet the CI had the drivers cached.
