### ISSUE TITLE
How to run Playwright in Linqpad

### ISSUE THREAD

**Issue by rolyv** [microsoft/playwright-sharp#1255]
I'm running the latest version of Linqpad (v. 6.12.4) with .net core 3.1.1. I imported Playwright via Linqpad Nuget interface. I've tried running `Playwright.InstallAsync()`, but I keep getting "PlaywrightSharpException: Driver not found in any of the locations." 

I was looking through issues and came across this change to how the drivers are installed: https://github.com/microsoft/playwright-sharp/pull/991/. I'm guessing that may have something to do with it since I don't seem to have a way to run `dotnet publish` command for a linqpad project. 

Wondering if anyone has any suggestions how to get Playwright running in Linqpad?

**Comment by dovydasm** [comment]
You have to specify the location of a platform specific driver. Go to `%userprofile%\.nuget\packages\playwrightsharp\`, choose one of the platforms and get the location of a cmd, then use that file path as an argument in `CreateAsync`.

`using var playwright = await Playwright.CreateAsync(driverExecutablePath :  cmdPath);`

**Comment by rolyv** [comment]
Thanks @dovydasm! That worked. This is what the driver path ended up being for me in case it helps anyone else: `driverExecutablePath: @"%userprofile%\.nuget\packages\playwrightsharp\0.192.0\Drivers\win-x64\native\playwright.cmd"`
