### ISSUE TITLE
Question: text selector issue.

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#1260]
Good day, 

As you might already know, text selectors have changed in 0.190.2 and some folks are having issues with it (including me)...
Now there will be a fix (rollback) for microsoft/playwright, as per, https://github.com/microsoft/playwright/pull/5690 in next release.

Not sure how the bases overlap so question is, will this then be fixed in playwright-sharp next release too? 

Thanks for this amazing piece of work....
-M

**Comment by kblok** [comment]
If there is a 1.9.2 in Playwright we will release a 0.192.0 here.

**Comment by kababoom** [comment]
Great, thank you @kblok
