### ISSUE TITLE
ArgumentException when publishing self contained

### ISSUE THREAD

**Issue by H4xX0r1337** [microsoft/playwright-sharp#1274]
You get the following exception when trying to run a self contained exe.

```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at PlaywrightSharp.Transport.Connection.GetExecutablePath()
   at PlaywrightSharp.Transport.Connection.GetProcess(String driverExecutablePath)
   at PlaywrightSharp.Transport.Connection..ctor(ILoggerFactory loggerFactory, TransportTaskScheduler scheduler, String driverExecutablePath, String browsersPath)
   at PlaywrightSharp.Playwright.CreateAsync(ILoggerFactory loggerFactory, TransportTaskScheduler scheduler, String driverExecutablePath, String browsersPath, String debug)
   at MyBot.Program.RunBot(String profileDir, Boolean firstStart)
   at MyBot.Program.Main()
   at MyBot.Program.<Main>()
```

**Comment by kblok** [comment]
Thanks for the report, we'll take a look at it

**Comment by avodovnik** [comment]
Hi, @H4xX0r1337 can you give us some more context around this error? Maybe an example to repro?

**Comment by aarivex** [comment]
> 
> 
> Hi, @H4xX0r1337 can you give us some more context around this error? Maybe an example to repro?

It's really simple to reproduce.

1. Create a new console application project (.NET 5)
2. Install PlaywrightSharp (NuGet/Install-Package)
3. Instantiate a new Playwright server and launch the browser. Sample code:
```csharp
using PlaywrightSharp;

namespace SelfContainedPlaywrightSharp
{
	class Program
	{
		static void Main(string[] args)
		{
			IBrowser browser = (Playwright.CreateAsync().Result)
				.Firefox
				.LaunchAsync()
				.Result;
				
			// ...
		}
	}
}
```
4. Deploy the application as self-contained (via command or through **Publish**)
```sh
dotnet publish -c Release -r win-x64 --self-contained true
```

5. Run the executable.
```
Unhandled exception. System.AggregateException: One or more errors occurred. (The path is empty. (Parameter 'path'))
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at PlaywrightSharp.Transport.Connection.GetExecutablePath()
   ...
```

I've cut the rest of the output because it was irrelevant.

**Comment by kblok** [comment]
Playwright won't work self-contained at the moment. Let's leave this open for further investigation. But it won't work right now.

On the other hand. I strongly recommend you to avoid blocker calls to `.Result`. You should be able to use `async/await` in your code.

**Comment by aarivex** [comment]
> 
> 
> Playwright won't work self-contained at the moment. Let's leave this open for further investigation. But it won't work right now.
> 
> On the other hand. I strongly recommend you to avoid blocker calls to `.Result`. You should be able to use `async/await` in your code.

I could've made the Main method asynchronous with `static async Task Main()`, but I don't really see a reason behind it.
Theres nothing else to do than to wait for the browser to launch, why should that be asynchronous? :P

My other projects in PlaywrightSharp on the other hand are running inside their respective custom Page classes (like the Page-Object Model), which are async.

Thanks for the fast reply though! Keen to follow this for the future, I hope there will be a solution soon.

**Comment by kblok** [comment]
>I could've made the Main method asynchronous with static async Task Main(), but I don't really see a reason behind it.
Theres nothing else to do than to wait for the browser to launch, why should that be asynchronous? :P

This is a good read :) https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by aarivex** [comment]
> 
> 
> > I could've made the Main method asynchronous with static async Task Main(), but I don't really see a reason behind it.
> > Theres nothing else to do than to wait for the browser to launch, why should that be asynchronous? :P
> 
> This is a good read :) https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

Thanks for the link! But I'm already aware of blocking scenarios and deadlocks 😅
Imagine a simple console application which will only be used by you and it simply starts up a browser, does its stuff and returns something to stdout. Just blocking things like `CreateAsync()` or `LaunchAsync()` wouldn't harm, since theres nothing else your application does in the meantime it waits for Playwright to create the server and launch the browser, right?

Or am I missing anything? o.Ô

**Comment by pavelfeldman** [comment]
As per comment above, we don't support self-contained mode.
