### ISSUE TITLE
How to properly handle async code in constructor - xunit case

### ISSUE THREAD

**Issue by 12masta** [microsoft/playwright-sharp#1280]
I am writing some e2e tests using playwright and I am run into issue/concerns. I am using xunit lib, so you probably know that there is no beforeEach hooks or something. To execute code before each test I am using constructor in the test class. This is how I handle the case:

```
        public RegistrationTests()
        {
            using var playwright = Playwright.CreateAsync().Result;
            var browser = playwright.Chromium.LaunchAsync(true).Result;
            var page = browser.NewPageAsync().Result;
            page.GoToAsync("https://bing.com").Result;
        }
```

Do you have some good practices in case of synchronous and asynchronous code?

**Comment by kblok** [comment]
I would like to create some library so you don't have to do that.
In the meantime you can use `IAsyncLifetime` which give you an `InitializeAsync` and a `DisposeAsync` method.

See https://github.com/microsoft/playwright-sharp/blob/main/src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserContextBaseTest.cs

**Comment by avodovnik** [comment]
You can also have a look at my answer on [StackOverflow](https://stackoverflow.com/a/65795172/319151) which gives an example of this. Feel free to re-open the issue, if you need more help, though.
