### ISSUE TITLE
Resource management in ASP.NET application

### ISSUE THREAD

**Issue by jonekdahl** [microsoft/playwright-sharp#1285]
Hi,

We're porting a ASP.NET service that renders PDF:s from PuppeteerSharp to PlaywrightSharp since this project seems to be the focus of development today. With Playwright, the memory usage has increased and there are a lot of `node` processes hanging around for a long time when we put some load on the service.

This is the method that renders a PDF, called once per request:

```csharp
        private async Task<byte[]> DoCreatePdf(string html)
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(headless:true, args: new[] { "--disable-dev-shm-usage" });
            var page = await browser.NewPageAsync();

            await page.SetContentAsync(html);
            return await page.GetPdfAsync(format: PaperFormat.A4, printBackground: true);
        }
```

Are we missing something? Is there another, better way to dispose of resources? Should we be reusing some of them instead of starting new instances on every request?

#### Versions

 * PlaywrightSharp: 0.191.2
 * .net runtime: 5.0.102
 * OS: Ubuntu 18.04

**Comment by pavelfeldman** [comment]
Yes, you should reuse playwright and browser. Create new context/page for each pdf generation call instead.
