### ISSUE TITLE
Could you provide an MSBuild option to skip the browser install

### ISSUE THREAD

**Issue by javiercn** [microsoft/playwright-sharp#1292]
Would it be possible to provide an MSBuild property to avoid installing browsers? Something around [here](https://github.com/microsoft/playwright-sharp/blob/main/src/PlaywrightSharp/build/netstandard2.0/PlaywrightSharp.targets#L15) like PlaywrightDisableBrowserInstall or similar. 

Building test projects on our CI agents causes the install to trigger and increases our build failure rate.

Thanks in advance!

**Comment by kblok** [comment]
Sounds like a good idea

**Comment by Jojoshua** [comment]
Would like to see this for all playwright configuration options such as 

PLAYWRIGHT_BROWSERS_PATH PLAYWRIGHT_DOWNLOAD_HOST
...ect

**Comment by pavelfeldman** [comment]
This is now fixed, browser installation is now a manual step, by default Playwright comes w/o browsers: https://playwright.dev/dotnet/docs/intro
