### ISSUE TITLE
Exporting to PDF with repeated images results in very large file sizes

### ISSUE THREAD

**Issue by benm-eras** [microsoft/playwright-sharp#1295]
If you use the same image repeatedly (e.g. logo in top corner of every page) then that image is embedded multiple times causing the file size to get very large for long documents. Each image should only be embedded once no matter how many times it is used, is there a way to accomplish this with playwright?

**Comment by pavelfeldman** [comment]
Sorry, out PDF is a result of printing, it does not optimize or dedupe.
