### ISSUE TITLE
Problem with IsJavascriptFunction and esprima

### ISSUE THREAD

**Issue by imlokesh** [microsoft/playwright-sharp#1296]
Consider the following js code:

```
function logme(msg) {
    console.log(msg);
}
    
logme('hello');
```

If it is added as an InitScript to the page with `page.AddInitScriptAsync`, it fails in chrome because the esprima javascript parser wrongly assumes that the script is a function.

The same expression works fine with playwright in nodejs.

Imo, the esprima parsing is doing more harm than good. Some scripts that will otherwise run fine in a modern browser fail esprima parsing.

I propose to remove esprima as dependancy and expose `isFunction` parameter wherever necessary.

**Comment by avodovnik** [comment]
This is something that we're actively working on, with the new API. @kblok and I had a few conversations about it.

**Comment by pavelfeldman** [comment]
With the latest API, you should wrap it with () => {}
