### ISSUE TITLE
How to keep Playwright page open?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-sharp#1297]
Hello:
I am new to Playwright-sharp, I want to use Chrome browser to visit some web site, and later on, I can run some JavaScript.  When it is idle, I want to keep the browser open. In Puppeteer-sharp, if I don’t close the page by code, it stays open. But in Playwright-sharp, after I show some data, the browser immediately closed, (after the beep sound). I can’t find any useful example on how to keep it open, so I can see the web page by eyes.
Here is my code now: (Playwright-sharp version 0.192.0 on Windows 10 Version 20H2; my IDE is Visual Studio 2019 Version 16.9.3, C# console project target on .NET 5.0)
`class Program
 {
  private static IPage page0;
  private static IPlaywright playwright;
  private static PlaywrightSharp.Chromium.IChromiumBrowser browser;
  private static PlaywrightSharp.Chromium.IChromiumBrowserContext context;

  static async Task Main()
  {
   playwright = await Playwright.CreateAsync();
   browser =
   await playwright.Chromium.LaunchAsync(new LaunchOptions { Headless = false });
   context = await browser.NewContextAsync();
   page0 = await context.NewPageAsync();
   await page0.GoToAsync("https://bing.com/");
   await page0.WaitForTimeoutAsync(4000);
   Console.Beep();
  }
 }
`
Any suggestions?

**Comment by imlokesh** [comment]
Just keep your program running by adding `await Task.Delay(-1)` or `Console.ReadLine()` after console beep.

**Comment by zydjohnHotmail** [comment]
Thanks:
It works!
