### ISSUE TITLE
Looking for help conversion SeleniumSharp code to PlaywrightSharp

### ISSUE THREAD

**Issue by alethcoe** [microsoft/playwright-sharp#1311]
Iam looking for help conversion SeleniumSharp code to PlaywrightSharp. I have migrated almost everything but I'm struggling with a screen shot reporter we have created.

We grab the element we are working with and then put a red border around. After we take the screenshot we reset the style. To show what was selected in our report.
```
 string originalStyle = element.GetAttribute("style");
 js.ExecuteScript("arguments[0].setAttribute('style', 'background: Aqua; border: 2px solid red;');", element); 
```

I was trying to do something like below,  But I am not able to get the style with Playwright. Any help would be appreciated. I looked through the unit tests but I didn't find anything like grabbing the style.
```
 string originalStyle = await element.EvaluateAsync( "e => e.getAttribute('style')");
 await element.EvaluateAsync("this.style.background = 'background';");
 await element.EvaluateAsync("this.style.border = '2px solid red';");
```

**Comment by kblok** [comment]
When you use the `EvaluateAsync` function of an  `ElementHandle`, the first argument of that function will be the element.
You could do something like this.

```
await element.EvaluateAsync("el => el.style.background = 'background';");
```

**Comment by alethcoe** [comment]
ok cool, so would I be able to  return the current background with just el => el.style.background or is there a different way besides getAttribute?

**Comment by kblok** [comment]
Yeah. You can do that using the generic `EvaluateAsync<string>`.
