### ISSUE TITLE
Guidelines / best practices for waiting for ajax requests to finish

### ISSUE THREAD

**Issue by matthiasploetz** [microsoft/playwright-sharp#1318]
I am looking for help concerning how to set up waiting pattern for ajax requests.

Here is the example method:
```
await page.SetInputFilesAsync("#file-upload-uploader", fileName);
await page.ClickAsync("#file-upload-ok");
var fileAdded = await page.IsVisibleAsync($"text='{fileName}'");
```

Setting the input files as well as clicking the file-upload-ok run ajax requests. If I am correct, this does not pick up as a navigation event. How would I wait for the file upload ajax request to be done? and then after clicking the file-upload-ok button, how would I wait for that second ajax request to be done before checking visibility of the fileName?

I am guessing there is an intended pattern to be used. I'd appreciate an example of how I could accomplish this.

**Comment by kblok** [comment]
`ClickAsync` will wait for the element to be visible and actionable. So if that's being shown after the file is ready you are good there.
If you want to check for visibility you could do something like this:

```
await Page.WaitForSelectorAsync($"text='{fileName}'", WaitForSelectorState.Visible)
```

**Comment by matthiasploetz** [comment]
ah, ok. I guess waiting for ajax requests to finish is more or less the same idea than simply waiting for the visibility of the element.
You need to time out the test in any case at some point if the element is not there.

I actually added a helper for the case where I want to make sure an element is not there; but get a quick response back:
```
        internal static bool isElementPresent(IElementHandle elementHandle) => elementHandle switch
        {
            ElementHandle => true,
            _ => false
        };
```
I use it with this pattern to make sure a test user does not have access to a file:
```
            var fileHandle = await page.QuerySelectorAsync(file);
            return isElementPresent(fileHandle);
```
Thank you for the quick response. I hope this helps someone else as well.
