### ISSUE TITLE
[Improvement] Consider generating IEnumerable<T> as params

### ISSUE THREAD

**Issue by avodovnik** [microsoft/playwright-sharp#1320]
We have a ton of methods, like `Task<IReadOnlyCollection<BrowserContextCookiesResult>> GetCookiesAsync(IEnumerable<string> urls = default);` that might be better off if we generated them as 
`Task<IReadOnlyCollection<BrowserContextCookiesResult>> GetCookiesAsync(param string[] urls);`

**Comment by kblok** [comment]
The rule would be if that's the only argument?
