### ISSUE TITLE
ARM / Raspberry Pi Support?

### ISSUE THREAD

**Issue by H4xX0r1337** [microsoft/playwright-sharp#1324]
Currently, PlaywrightSharp does not work at all when being run on an Raspberry Pi. I would find support for it pretty usefu. 
Is ARM support planned?

**Comment by kblok** [comment]
The main goal of Playwright-Sharp is UI Testing. I don't see that we need to support UI Testing in Raspberry Pi.

**Comment by H4xX0r1337** [comment]
@kblok Why would you exclude arm support? Is there any reason it won't work on it. It would be very useful for writing bots, but you can also use it for automating tests, for example you could host a gitlab server on the pi and automatically run the playwright tests.
Also, the new M1 macs will very likely not work natively with Playwright.
Overall, I can't see how ARM support would hurt.

**Comment by pavelfeldman** [comment]
We don't support Pi, we do support M1 though.

**Comment by H4xX0r1337** [comment]
> We don't support Pi, we do support M1 though.

What is the difference though? Is ARM only supported on macOS?
