### ISSUE TITLE
Failed to download chromium in test project

### ISSUE THREAD

**Issue by Jojoshua** [microsoft/playwright-sharp#1373]
Trying to get this setup in a test project and getting failures:

connect ETIMEDOUT 13.107.213.40:443
Failed to download chromium, caused by
The command "playwright.cmd install" exited with code 1.

1. Is this a Microsoft owned IP ?
2. Is there a way to specify proxy settings during this outreach attempt?

**Comment by kblok** [comment]
Hey @Jojoshua.
1. It is.
2. Playwright will try to download the required browsers during the build. If you need to set up a proxy, you could run `playwright.cmd install` manually (you will find it in your bin folder). This link will help you setup a proxy https://playwright.dev/docs/installation#install-behind-the-firewall-or-proxy

**Comment by Jojoshua** [comment]
Hey @kblok , thanks for the quick reply! No luck so far getting the right mix going. Doing testing on my home environment I see that doing npm install of playwright vs the playwright-sharp install will provide different browsers. The result install of the npm install won't satisfy the playwright-sharp browser requirement as I think they are looking for different browser versions. 

However taking a different perspective, as a .NET developer I wouldn't necessarily know or expect to have to dig into npm configuration to get playwright-sharp setup.

Could we have a .NET flavor of matching configuration where if you add some well defined configuration keys in your project's appSettings it would override if available? I feel like this would also help certain CI/CD scenarios as well.

For example..
<add key="PLAYWRIGHT_BROWSERS_PATH" value="App_Data\\browsers" /> 
<add key="PLAYWRIGHT_DOWNLOAD_HOST" value="https://13.107.213.40:443" />
<add key="PLAYWRIGHT_FIREFOX_DOWNLOAD_HOST" value="https://13.107.213.40:443" />

**Comment by kblok** [comment]
That makes totally sense @Jojoshua

**Comment by kblok** [comment]
@Jojoshua could you try this with your proxy? So, instead of calling npm install call the driver install

```
set HTTPS_PROXY=https://192.168.1.78
playwright.cmd install
```

**Comment by Jojoshua** [comment]
@kblok so exactly how should I run that?

This is what I tried..
I opened up a powershell session with the root being \\Debug\.playwright\win-x64\native
Then ran set HTTPS_PROXY=http://proxy:80   *note that I'm not sure if we have our internal proxy as https but i've heard it is http
Then I ran .\playwright.cmd install but got same error

t also may be that our proxy requires authentication as well. I also tried set HTTPS_PROXY=http://user:pw@proxy:80 but that did not work either.

Do these set commands write anything to disk or are they only for your powershell session in memory?

**Comment by Jojoshua** [comment]
@kblok How can I just bypass this automated setup and manually configure the browsers so that playwright-sharp thinks everything is good to go?

I found in source code the CDN locations and I am able to download zips directly.
For example I can grab https://playwright.azureedge.net/builds/chromium/857950/chromium-win64.zip 

What would be the correct URLs(chromium,Firefox,FFMpeg) I would need to grab and where should they be unzipped to?

**Comment by Praneet-Srivastav** [comment]
I am stuck at the same issue. I am behind a proxy and  not sure how do I pass the proxy detail to playwright sharp setup.

**Comment by Jojoshua** [comment]
I ended up just manually downloading each requirement by mapping the name/revision from the browsers.json file then unzipping into C:\Users\[user]\AppData\Local\ms-playwright with the appropriate named folder and adding a INSTALLATION_COMPLETE file as well.

**Comment by pavelfeldman** [comment]
This typically happens due to a misconfigured proxy. Please feel free to reopen if this still is an issue.

**Comment by Jojoshua** [comment]
> This typically happens due to a misconfigured proxy. Please feel free to reopen if this still is an issue.

@pavelfeldman could we still consider the feature request from my 2nd posting? We still need a nice way to customize the environment/install variables in a
.Net way.
