### ISSUE TITLE
Enable CLI integration for Playwright

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#1383]

**Comment by avodovnik** [comment]
The goal for this issue isn't necessarily to bring back the `PlaywrightSharpTool`, but to enable the CLI integration, specifically, we need to be able to run `codegen` from the command line. 

One option to do this, would definitely be to use a `dotnet tool`, but that is generally fairly clunky. It would require:

1) We push a separate package, i.e. `Microsoft.Playwright.CLI` 
2) Users would have to separately run `dotnet tool install Microsoft.Playwright.CLI` to get a command, i.e. `pw-cli`
3) They can then run `pw-cli codegen`

The problems/drawbacks here are:
- This isn't necessarily tied to the project they're working on (i.e. the tool can be installed globally)
- That also means there might be a version mismatch - the tool has to be manually & separately updated (`dotnet tool update`) which the users may or may not end up doing
- We need to come up with a name that doesn't conflict (i.e., it can't be `playwright`)

Meanwhile, while definitely not_sexy_, the user can run the codegen facility now by doing: 
```
 .\src\Playwright.Demos\bin\Debug\net5.0\.playwright\win-x64\native\playwright.cmd codegen https://www.wikipedia.org
```
