### ISSUE TITLE
Reuse authentication state is not work

### ISSUE THREAD

**Issue by interiv** [microsoft/playwright-sharp#1459]
public async Task a()
        {
            var playwright = await Microsoft.Playwright.Playwright.CreateAsync();

            var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions()
            {
                Headless = false,
                Channel = "msedge-canary",
                SlowMo = 50,
            });

            var userCookiesFilePath = Path.Combine(Application.StartupPath, "用户");
            string path = Path.Combine(userCookiesFilePath, "storage-state.json");

//==========================
            var context2 = await browser.NewContextAsync(new BrowserNewContextOptions { StorageStatePath = path });
            var page2 = await context2.NewPageAsync();
            await page2.RouteAsync("**/*", (route) =>
            {
                route.FulfillAsync(new RouteFulfillOptions { Body = "<html>page2</html>" });
            });

            await page2.GotoAsync("https://www.example.com");

            await page2.EvaluateAsync(@"() =>
            {
               document.write('abc'+document.cookie+'abc');
            }");

           //==========================
 var context = await browser.NewContextAsync();

            var page1 = await context.NewPageAsync();
            await page1.RouteAsync("**/*", (route) =>
            {
                route.FulfillAsync(new RouteFulfillOptions { Body = "<html>page1</html>" });
            });

            await page1.GotoAsync("https://www.example.com");

            await page1.EvaluateAsync(@"() =>
            {
                localStorage['name1'] = 'sadfasdfasdf';
                document.cookie = 'username=asdfasdfasdfasdf Doe';
            }");
            await page1.EvaluateAsync(@"() =>
            {
               document.write('abc'+document.cookie+'abc');
            }");

            string storage = await context.StorageStateAsync(new BrowserContextStorageStateOptions { Path = path });

//==========================

           var context3 = await browser.NewContextAsync(new BrowserNewContextOptions { StorageStatePath = path });
            var page3 = await context3.NewPageAsync();
            await page3.RouteAsync("**/*", (route) =>
            {
                route.FulfillAsync(new RouteFulfillOptions { Body = "<html>page3</html>" });
            });

            await page3.GotoAsync("https://www.example.com");
            await page3.EvaluateAsync(@"() =>
            {
               document.write('abc'+document.cookie+'abc');
            }");

           // await page3.GotoAsync("https://www.example2.com");

        }

I do not know why.

I saw  src\Playwright.Tests\BrowserContextStorageStateTests.cs

 public async Task ShouldRoundTripThroughTheFile()
        {
            var page1 = await Context.NewPageAsync();
            await page1.RouteAsync("**/*", (route) =>
            {
                route.FulfillAsync(new RouteFulfillOptions { Body = "<html></html>" });
            });

            await page1.GotoAsync("https://www.example.com");
            await page1.EvaluateAsync(@"() =>
            {
                localStorage['name1'] = 'value1';
                document.cookie = 'username=John Doe';
            }");
            using var tempDir = new TempDirectory();
            string path = Path.Combine(tempDir.Path, "storage-state.json");
            string storage = await Context.StorageStateAsync(new BrowserContextStorageStateOptions { Path = path });
            Assert.AreEqual(storage, File.ReadAllText(path));

            await using var context = await Browser.NewContextAsync(new BrowserNewContextOptions { StorageStatePath = path });
           .........>>>>>>var page2 = await context.NewPageAsync();
          ...........>>>>>>await page.RouteAsync("**/*", (route) =>
            {
                route.FulfillAsync(new RouteFulfillOptions { Body = "<html></html>" });
            });

            await page.GotoAsync("https://www.example.com");
            Assert.AreEqual("value1", await page.EvaluateAsync<string>("localStorage['name1']"));
            Assert.AreEqual("username=John Doe", await page.EvaluateAsync<string>("document.cookie"));**
        }

page ? not page2 ?

**Comment by interiv** [comment]
I saw the java test code here

https://github.com/microsoft/playwright-java/blob/master/playwright/src/test/java/com/microsoft/playwright/TestBrowserContextStorageState.java

make sure  c# test code has a bug;

**Comment by avodovnik** [comment]
@interiv this issue should have been closed when https://github.com/microsoft/playwright-sharp/pull/1460 was merged, right?

**Comment by pavelfeldman** [comment]
My understanding is that this is fixed.
