### ISSUE TITLE
EvaluateAsync arg serialization issue

### ISSUE THREAD

**Issue by thomaschanneladvisor** [microsoft/playwright-sharp#1476]
Hey, i am passing an object into the EvaluateAsync method along with my .js script.
`var playwrightResult = await Page.EvaluateAsync(expression: code, arg: myArg);`

my script would look something like this

```
(myArg) => {
//do stuff with document and myArg here and return
}
```

When i execute this code i get an exception.
The exception message i receive is
`arg.value.o[11].v: expected object, got string`
Exception type - PlaywrightSharpException
some of the stack trace if that would be helpful

>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PlaywrightSharp.Transport.Connection.<SendMessageToServerAsync>d__221.MoveNext() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 186
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
>    at PlaywrightSharp.Frame.<EvaluateAsync>d__142.MoveNext() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Frame.cs:line 679
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Is my use incorrect ? (I am using a similar approach for PuppeteerSharp without issue) or is there an issue in the library ?

**Comment by kblok** [comment]
@thomaschanneladvisor that sounds like a but. Can you share a class model that breaks the serialization process?

**Comment by thomaschanneladvisor** [comment]
@kblok I have done a little more testing by removing different property types from my class , I narrowed it down to an enum.
I can work around this since I do not use this in the arg i pass in.
Here is a basic class that i can repro it on. I just new it up and pass it into the arg param.

`  public class TestArg
    {
        public TestPWEnum TestPWEnum { get; set; }
    }

    public enum TestPWEnum
    {
        Test
    }
`

**Comment by kblok** [comment]
Thank you @thomaschanneladvisor. I will definitely take a look at it :)
