### ISSUE TITLE
[Docs] How versions work

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-sharp#636]
I've seen some users assume that playwright-sharp latest is equivalent to playwright latest. Would it be useful to add a readme section to explain how the version matching between playwright-sharp and playwright works? Happy to send a PR if this sounds good.

**Comment by kblok** [comment]
Our Readme needs some love for sure. PRs are welcome :)

To be on the same page, and based on the Core Guidelines I mentioned [here](https://www.hardkoded.com/blog/its-playwright-time):

>We won’t (technically speaking) respect semver. We will always try to match Playwright’s versions, so you will know that e.g., PlaywrightSharp 1.5, will have the same features as Playwright 1.5.

We won't consider revisions there. That would give us some room for our own hotfixes.
