### ISSUE TITLE
A navigation issue

### ISSUE THREAD

**Issue by julian-code** [microsoft/playwright-sharp#640]
I'm trying to port my puppeeter app to PlayWright sharp.

However, Im having problems with the following code:

```
var url = "https://yoyo-wb-prod.azurewebsites.net/";
var chrome = new ChromiumBrowserType();
ConnectOptions options = new ConnectOptions()
{
    BrowserWSEndpoint = "ws://localhost:3000"
};
await using var browser = await chrome.ConnectAsync(options);
var page = await browser.DefaultContext.NewPageAsync();
await page.GoToAsync(url);
```

It gives following error message:
PlaywrightSharp.NavigationException : Navigation to https://yoyo-wb-prod.azurewebsites.net/ was canceled by another one

The site it self redirects to a SSO site for login.

**Comment by kblok** [comment]
We are not supporting `ConnectAsync` now.  If you have a use case scenario where `ConnectAsync` is needed, please open a new issue sharing your that use case scenario.

**Comment by dman777** [comment]
I would really like to have this. It would also be comparable to cypress `--no-exit` feature.
