### ISSUE TITLE
Final API review

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#641]

**Comment by dgozman** [comment]
From offline discussion:

1. Finish the named arguments conversion.
2. Remove BrowserType.Connect and BrowserType.LaunchServer (these will change between 1.1 and 1.4).
3. Generate interfaces with doc comments, see the difference with current ones, decide what to do.
4. Figure out whether we should provide overload with LaunchOptions and similar large options, next to the named arguments version.
5. Align api with 1.2, where rpc server is available.


For 1.4:
1. There is a list of client-side handling logic that should be done in C#, to support remote connect, like saving screenshots to the file.
2. Implement BrowserType.Connect similar to upstream (subject to change).
