### ISSUE TITLE
Checkbox handling missing?

### ISSUE THREAD

**Issue by NTTAKR** [microsoft/playwright-sharp#797]
Hi all, 

I was extremely happy with the operations with PlayWrightSharp, until I reached the task to read and write states of checkboxed. 
In playwright (for node) there are some methods called check and uncheck, but those do not seem to exist in PlayWritghtSharp. 

Anybody solved this already? 

Thanks
   Andreas

**Comment by kblok** [comment]
@NTTAKR We are going to launch a new version with Check support. Stay tunned :)

**Comment by NTTAKR** [comment]
That's really good news. Any suggestion on timeframe? If it is not too extensive I would wait. I used puppeteer in node.js before, and the amount of code you have to write around the functions to handle correctly is gigantic.

**Comment by kblok** [comment]
@NTTAKR I hope we can ship it early next week, maybe by the end of this week.

**Comment by NTTAKR** [comment]
Great news. I'll definitely wait for that rather than choosing another framework. 
Thanks for your good work. What I've seen up to now really impressed me.

**Comment by kblok** [comment]
@NTTAKR Can you try now with v.0142.0?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
