### ISSUE TITLE
Error On Win 7

### ISSUE THREAD

**Issue by tungphan899** [microsoft/playwright-sharp#871]
Sorry for my bad english.
I am using win 7 - 64bit for testing playwrightsharp.
But when i just LaunchAsync, i see the error : 

PlaywrightSharp.Chromium.ChromiumProcessManager1
Exception thrown: 'System.PlatformNotSupportedException' in mscorlib.dll
Error On Start : The WebSocket protocol is not supported on this platform.

I see TransportFactory can set another WebSocket, but its not the same as PuppeteerSharp.

CONNECT_OPTIONS.TransportFactory = (uri, socketOptions) => { return SystemClientWebSocket.ConnectAsync(uri, cancellationToken); };

Anyone please help.

**Comment by kblok** [comment]
Could you explain your use case scenario? 
We are temporary for removing the Connect feature for v1.4, untill we figure out a better way to solve that with RPC. Your scenario will help us shape that feature.

Your english is great :)

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
