### ISSUE TITLE
DownloadsFolder

### ISSUE THREAD

**Issue by nor0x** [microsoft/playwright-sharp#874]
Hi all 👋
first of all - thanks for building playwright-sharp it's an incredible tool. I'm just migrating from puppeteer-sharp (also great btw) and was wondering if there is the possiblity to specify a `DownloadsFolder` like in the `puppeteer-sharp` `BrowserFetcher`
https://github.com/hardkoded/puppeteer-sharp/blob/a29f5f419fce89c701ebebbe7f6d9cb3f5f84b57/lib/PuppeteerSharp/BrowserFetcher.cs#L48

it would be helpful for my usecase to set a specific path where the downloaded browsers should live.

**Comment by kblok** [comment]
We can get that for the next version :)

**Comment by nor0x** [comment]
sounds great! thanks for the quick reply 👏 
out of curiosity do you already have an ETA for that?

**Comment by kblok** [comment]
We are reviewing the final API with the Playwright team. I hope it's a next week thing
