### ISSUE TITLE
LINQPad output flooded with tracing info

### ISSUE THREAD

**Issue by ghuser123321** [microsoft/playwright-sharp#877]
Playing around with this in LINQPad. Unfortunately the output window is flooded with internal traces. Is there any way to turn this off? Thanks a lot. 

![image](https://user-images.githubusercontent.com/71881005/94261796-bd717b00-ff32-11ea-81cf-ea89ae50e68a.png)

**Comment by kblok** [comment]
Thanks for the feedback @ghuser123321. We can improve that.

**Comment by Meir017** [comment]
Can we remove the `Debug.WriteLine` calls? each one is followed by a `_logger?.LogInformation`

**Comment by rolyv** [comment]
Not related to the OP issue, but I haven't been able to get Playwright running in Linqpad and I'm really curious how to do it. It looks like something may have changed recently that isn't playing nicely, but I may be wrong. Any pointers?

**Comment by kblok** [comment]
@rolyv do you want to create a new issue?

**Comment by rolyv** [comment]
Sure
