### ISSUE TITLE
Request: Selective browser install

### ISSUE THREAD

**Issue by slang25** [microsoft/playwright-sharp#890]
The playwright sharp tool to install browsers has an `install-browsers` command, however it would be nice to offer the ability to install a particular browser in the case where you know you will be only using chromium for example.

For me an `install-browsers` command is sufficient, but I would like to be able to only download what I use. I imagine there will be runtime checks for the presence of the browser regardless of the level of granularity they are acquired.

Pros:
- Less to download during CI

Cons:
- Another command
- More potential to have a mismatch of required browser at runtime, and installed browser

Related: #889

**Comment by mxschmitt** [comment]
For reference, upstream issue: https://github.com/microsoft/playwright/issues/3866

**Comment by mxschmitt** [comment]
cc @kblok its now possible by forwarding the browsers as CLI arguments, see here for the implementation: https://github.com/microsoft/playwright/pull/4952

**Comment by kblok** [comment]
Thanks for the heads up @mxschmitt. We are planning to implement this but not at runtime.

**Comment by pavelfeldman** [comment]
Browsers are now opt-in. See https://playwright.dev/dotnet/docs/intro
