### ISSUE TITLE
[Question] debug=pw:api

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#900]
First of all thank you for your hard work.....

After running some tests overnight we see the fill command failing occasionally with the following internal exception.

```
================= elementHandle.fill logs =================
[api] elementHandle.fill("somestring")
[api]   waiting for element to be visible, enabled and editable
[api]   element is visible, enabled and editable
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

Is there anyway to set the pw:api variable to further investigate ?

Thanks,
-M

**Comment by kblok** [comment]
@kababoom in what OS are you running the tests?

**Comment by kblok** [comment]
Hey, @kababoom I think we won't be able to enable `pw:api` yet. If we pass that env variable, Playwright would print the log on the stdout, breaking the driver.

Let me see what we can do.

**Comment by mxschmitt** [comment]
@kblok in Playwright for Python we redirect the stderr from the sub process to the stderr of the main process. The debug outputs will get printed to the stderr not to the stdout so it should work.

**Comment by kababoom** [comment]
Thanks, both of you...

Workaround is to use Type, that does work on this element fine.
Would you be interested in getting the debug log for this Fill error? if so I can run the same script in nodejs of course.

Thanks,
-M
