### ISSUE TITLE
Reduce nuget package size

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-sharp#912]
The nuget package size is currently 90MB, the uncompressed size is 141MB

I'm pretty sure this is related to https://github.com/microsoft/playwright-sharp/blob/0f6a1a713ec0e7bd6ac1688017dfd9f8a25b7dc4/src/PlaywrightSharp/PlaywrightSharp.csproj#L39-L52

I think we should be able to create a dll that contains the specific executable for each platform, then when installing the package we would download the correct dll.
perhaps we could do something like this https://stackoverflow.com/a/39036877/7025656 ?

**Comment by kblok** [comment]
I'm open to any improvement here. Just two things to consider:
1. afaik install scripts are not supported anymore (https://devblogs.microsoft.com/nuget/NuGet-3-What-and-Why/). If we find a solution it needs to be cross-platform.
2. The development environment might differ from the production environment. You should be able to code on Windows and ship it to a Linux server.

**Comment by Meir017** [comment]
perhaps we could implement this in a similar way to how the go version is doing it? they download the required driver from a remote server
https://github.com/mxschmitt/playwright-go/blob/db840fd1600c12c50e7dd0b83d5f97c434308bda/run.go#L29-L81

**Comment by kblok** [comment]
Yeah, there is an open debate there. What is preferable a fat dll or and extra install step?

**Comment by Telavian** [comment]
I prefer a fat dll personally.

**Comment by DavidZidar** [comment]
Do you need to target both `netstandard2.0` and `netstandard2.1`? This effectively doubles the NuGet package because both assemblies include all four zips as embedded resources.

**Comment by kblok** [comment]
That's a good point @DavidZidar. I was using 2.1 features in the early stages. I need to double-check that but I think we can remove 2.1

**Comment by Meir017** [comment]
could we drop the 2.x and use .net5 instead?

**Comment by kblok** [comment]
@Meir017 wouldn't that leave most users out?

**Comment by Meir017** [comment]
.net5 is supposed to go GA in the next month. I'm pretty sure all Microsoft's .net projects are targeting net5 so this makes sense to me

**Comment by Telavian** [comment]
.net 5 is not production ready.

**Comment by kblok** [comment]
@Meir017 I think a big part of the community will remain on .NET Framework and .NET Core 3.1 in the next few years. Also .NET 5 won't be LTS

**Comment by DavidZidar** [comment]
If you want to support .NET Framework you must use `netstandard2.0`, if you don't want that but want to support .NET Core 3.1 which will be the LTS release until .NET 6 you can use `netstandard2.1` instead. If you target `net5.0` everyone using anything below .NET 5 is left out.

What you can do if you want the most reach but still get newer compiler compiler warnings such as nullability is target both `netstandard2.0` and `net5.0` but only publish `netstandard2.0`, or you can put the zip files in a separate assembly.

**Comment by Meir017** [comment]
v0.151.0
![image](https://user-images.githubusercontent.com/9786571/97440562-4748a580-1930-11eb-9f5d-0eb96fa30724.png)

v0.152.0
![image](https://user-images.githubusercontent.com/9786571/97440586-4f084a00-1930-11eb-8cf1-99af323acff0.png)

almost 40MB smaller 👍

**Comment by kblok** [comment]
Fixed with the last refactor.
