### ISSUE TITLE
Switch TAB

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#914]
We are running a couple of flows with PlaywrightSharp now and we are very happy with speed and stability so far so a big thank you ...

One flows we got trouble with migrating is a flow that opens and activates a new tab when clicking on an element. Now the question, how can we continue our tests on that newly opened tab? 

We did try to get the pages but that does not seem to be implemented.

Thanks,
-M

**Comment by kblok** [comment]
Did you try something like this? https://github.com/microsoft/playwright-sharp/blob/61ad43519ff23a5403c81c8feb280823af101dde/src/PlaywrightSharp.Tests/BrowserContext/EventsBrowserContextPageTests.cs#L32

**Comment by kababoom** [comment]
No, to be honest not sure how this would help.
We now change the attribute to open in the current tab.

`element.EvaluateAsync<string>("e => e.setAttribute('target', '_top')")`

Thanks,
-M

**Comment by kblok** [comment]
You could do something like this

```cs 
var pageTask = context.WaitForEvent(ContextEvent.Page, e => e.Page.Url == UrlToCheck);

await Task.WhenAll(
    pageTask,
    element.ClickAsync());

var newPage = pageTask.Result.Page;
```

**Comment by kababoom** [comment]
Thank you this works..

Since the url is partly dynamic we use: 
`var pageTask = context.WaitForEvent(ContextEvent.Page, e => e.Page.Url.Contains("/nondynamicpart"));`

Cheers,
-M

**Comment by kblok** [comment]
Can we close this one @kababoom ?
