### ISSUE TITLE
docs: Update logo in the site

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#920]

**Comment by flinde** [comment]
Is this issue for updating the logo (<img id="logo" class="svg" src="logo.svg" alt="">) in https://github.com/microsoft/playwright-sharp/blob/gh-pages/index.html  with 🎭?
And how does the gh-page branch relates to the main branch, will they be merged in the future?

**Comment by kblok** [comment]
Yes! and if we can get a favicon that would be great.

We are using [docfx](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html). The project is on the `docfx_project` folder. When we ship a new version, the `gh-page` branch is updated.

You can test the site locally using `docfx serve` on the `docfx_project` folder.

I'm using the template directory in [other projects](https://github.com/hardkoded/puppeteer-sharp/blob/master/docfx_project/docfx.json#L63) to accomplish this.

**Comment by flinde** [comment]
Thank you for the clarification.
