### ISSUE TITLE
Click invisible element

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#923]
Apologies, another one, we don't seem to be able to click an 'invisible item'..
The item becomes visible via mouseover but is clickable when hidden nevertheless (verified).

We tried a couple of settings with the force option but without succes.
`ClickAsync("#button1", 0, MouseButton.Left, 1, null, null, null, true, null);`

What are we doing wrong?

Thanks,
-M

**Comment by Meir017** [comment]
the might be a general issue with playwright and not in the .NET binding, 
does this work using the nodejs library? (https://github.com/microsoft/playwright)

**Comment by kblok** [comment]
@kababoom You could pass `force: true` which bypasses the [actionability checks](https://playwright.dev/#version=v1.4.2&path=docs%2Factionability.md&q=)

**Comment by kababoom** [comment]
Thanks, the force was actually what we tried with this # version but could be we did not use the options correctly:
`ClickAsync("#button1", 0, MouseButton.Left, 1, null, null, null, **_true_**, null);`

Using the nodejs version.
`await page.click("#button1");` Does not work.

`await page.click("#button1", {force: true});` Does not timeout but does not click the button (correctly) either which is unexpected since a simple console click does work fine on element hidden or not.
`document.getElementById("button1").click();`

Got me puzzled so idea's welcome ..
-M

**Comment by kblok** [comment]
Just a side note here. You can take advantage of named arguments here :) 

```cs 
page.ClickAsync("#button", force: true);
```

**Comment by kblok** [comment]
@kababoom Didn't you try to hover over the button before clicking? just as a test?

**Comment by kababoom** [comment]
Thanks Dario,

Named argument was also tried.

When hoovering it does work since then the element goes out of hidden.

-M

**Comment by kblok** [comment]
Is there any chance to take a look at that page?

**Comment by kababoom** [comment]
Got two different pages but both are of our customers.
Will see if I can find an open page.

-M

**Comment by kababoom** [comment]
This gives an exception, element not visible.

```
            await page1.GoToAsync("https://www.w3schools.com/howto/howto_css_dropdown.asp");
            //await page1.ClickAsync("#accept-choices");
            await page1.ClickAsync("text=Link 1", force: true);
```
"One or more errors occurred. (Element is not visible
=========================== logs ==========================

-M

**Comment by kblok** [comment]
@kababoom I was able to solve this using mouse emulation. What do you think?

```cs
await page.GoToAsync("https://www.w3schools.com/howto/howto_css_dropdown.asp");
var btn = await page.QuerySelectorAsync(".dropbtn");
var box = await btn.GetBoundingBoxAsync();
await page.Mouse.MoveAsync(box.X + (box.Width / 2), box.Y + (box.Height / 2));
var option = await page.QuerySelectorAsync("text=Link 1");
var optionBox = await option.GetBoundingBoxAsync();
await page.Mouse.MoveAsync(optionBox.X + (optionBox.Width / 2), optionBox.Y + (optionBox.Height / 2));
await option.ClickAsync();
```

**Comment by kababoom** [comment]
Thanks Dario.....

The mouse move is useful code to have but it's a lot of code for something simple. Wonder how reliable it is and if this works in headless mode, or with multiple windows on top of each other will the mouse moves interfere?

There are easier ways to work around this, we load some js script with functions like the querySelectorDeep from GeorgeGriff and click from there. But not sure how far we can go messing around in the Dom without Playwright knowing.

Curious though why it's so difficult to click on hidden elements (did not look into the code yet).

Cheers,
-M

**Comment by kblok** [comment]
@kababoom the idea of the `ClickAsync` function is to emulate a user action. If the element is not visible there's no chance of a user action.

`ClickAsync` is not a map of the `click` function in javascript. If you want to use the `click` function you can use `EvalOnSelectorAsync`.

```cs
await page.EvalOnSelectorAsync("#button1", "el => el.click()");
```

**Comment by kababoom** [comment]
> @kababoom the idea of the `ClickAsync` function is to emulate a user action. If the element is not visible there's no chance of a user action.

Which is very useful but what then is the force: true for?

Thanks,
-M

**Comment by kblok** [comment]
@kababoom `force` bypasses non-essential checks (https://playwright.dev/#version=v1.5.1&path=docs%2Factionability.md&q=). For instance [Receiving Events](https://playwright.dev/#version=v1.5.1&path=docs%2Factionability.md&q=receiving-events).
But it won't bypass real user emulation.

**Comment by kababoom** [comment]
Alright, we assumed it would bypass the visible check, thanks for clearing this up..

Thanks,
-M
