### ISSUE TITLE
Exception when specifying format for page.GetPdfAsync

### ISSUE THREAD

**Issue by lvmajor** [microsoft/playwright-sharp#929]
When specifying the format for pdf generation, an exception is thrown as a string is expected but an object is passed (of type `PaperFormat`). The actual call site where the conversion should be done I think would be [here](https://github.com/microsoft/playwright-sharp/blob/4d9d2d26fa0998c1bdf88dcfa5dd517f8cd082b7/src/PlaywrightSharp/Transport/Channels/PageChannel.cs#L507)

**Comment by kblok** [comment]
Thanks for the report @lvmajor

**Comment by kblok** [comment]
Could you try 0.142.2?

**Comment by lvmajor** [comment]
Yes certainly

**Comment by lvmajor** [comment]
That seems to work :) I didn't see any code commit, did you update nuget from local source?

**Comment by kblok** [comment]
@lvmajor yeah, I wanted to get you unblocked :)

**Comment by lvmajor** [comment]
Ahah ok no problem I will keep it open even though the temporary fix works well for me :) I was not solely blocked by this hehe, I'm still struggling to get the html content size to be as expected but those conversions from css to inches... never really seem to work as expected ahah!
