### ISSUE TITLE
Mouse / Wheel Scrolling

### ISSUE THREAD

**Issue by nor0x** [microsoft/playwright-sharp#933]
i was wondering if there is a similar function like `Mouse.WheelAsync(x,y)` as in `PuppeteerSharp` in Mouse.cs https://github.com/hardkoded/puppeteer-sharp/blob/4c7a0bbf96a0cba7edec5c76bf7528fb4f5312d8/lib/PuppeteerSharp/Input/Mouse.cs#L139

Or do we have an other mechanism to simulate scrolling on a page?

thanks

**Comment by kblok** [comment]
Would `ElementHandle.ScrollIntoViewIfNeededAsync` help?

There is an ongoing discussion upstream https://github.com/microsoft/playwright/issues/1115

**Comment by nor0x** [comment]
thanks for the info - i will have a look in the upstream. In my case i would simulate mouse wheel scrolling, without any specific DOM elements.

currently i'm using this script to achieve this - where `x` and `y` are my scrolling deltas:

`page.EvaluateAsync($"window.scroll(window.scrollX + {x}, window.scrollY + {y})");`

**Comment by kblok** [comment]
@nor0x feel free to share your use case scenario in that issue.

**Comment by nor0x** [comment]
sure @kblok  i will follow up in the playwright repo. thank you very much :-)

**Comment by kblok** [comment]
cc @JoelEinbinder

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/1115
