### ISSUE TITLE
update playwright-sharp project description 

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-sharp#950]
I think this should match the tags in https://github.com/microsoft/playwright-python
![image](https://user-images.githubusercontent.com/9786571/96361232-b6521d00-112c-11eb-837e-8aafabc44bdf.png)

`playwright-sharp`:
![image](https://user-images.githubusercontent.com/9786571/96361225-a1758980-112c-11eb-887b-f491a9ff2a1f.png)

**Comment by kblok** [comment]
Done, thanks!
