### ISSUE TITLE
Timeout > 30000

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#952]
Hi Again,

We don't seem to be able to set the timeout > 30000ms.

Taking below from the test examples will work fine below 30000, above there's something else that times out at 30000 but what?
```
[Fact(Timeout = PlaywrightSharp.Playwright.DefaultTimeout)]
public async Task ElementHandleWaitForSelectorShouldTimeout()
{
    await Page.SetContentAsync("<div></div>");
    var div = await Page.QuerySelectorAsync("div");
    var exception = await Assert.ThrowsAnyAsync<TimeoutException>(() => div.WaitForSelectorAsync("span", WaitForState.Attached, 100));
    Assert.Contains("Timeout 100ms exceeded.", exception.Message);
}
```

LauchOptions timeout, page.defaultTimeout, page.navigationTimeout do not seem to change this.

Thank you,
-M

**Comment by kblok** [comment]
@kababoom, I know what it is. I'm working on 0.151.0. You'll get a fix in the next few days.

**Comment by kababoom** [comment]
I confirm this to be resolved.

Thank you Dario for you amazing work, it's fast and stable....... 

Cheers,
-M
