### ISSUE TITLE
GetPageAsync throws PlaywrightSharp.PlaywrightSharpException

### ISSUE THREAD

**Issue by florianwachs** [microsoft/playwright-sharp#953]
Hi there,
thanks a lot for PlaywrightSharp!

PlaywrightSharp.PlaywrightSharpException: 'Protocol error (Page.printToPDF): PrintToPDF is not implemented' is thrown.
I tried different parameters but it's failing.

## Environment
- Windows 10 Enterprise
- PlaywrightSharp 0.142.2
- .Net 5 RC 2
- Visual Studio 2019 Preview (newest)

## Step / Code to reproduce

```csharp
 await Playwright.InstallAsync();
 var playwright = await Playwright.CreateAsync();
 await using var browser = await playwright.Chromium.LaunchAsync(headless: false);
 var page = await browser.NewPageAsync();
 await page.GoToAsync("https://bing.com");
 await page.GetPdfAsync(path: "Test.pdf");
```

**Comment by kblok** [comment]
Hey @florianwachs! 
Export to PDF only works in headless mode.

**Comment by florianwachs** [comment]
I`m sorry, didn´t know that. Thanks!
