### ISSUE TITLE
ms-playwright-print-deps.exe as malware while running on server?

### ISSUE THREAD

**Issue by benhysell** [microsoft/playwright-sharp#959]
I've implemented Playwright in my asp.net core application so I can programmatically print a pdf a page from our Blazor client side application.

In development, and in servers that I control, this works like a charm.  Runs without issue in debug and release modes.

However when I deploy to servers I have a bit less control over, i.e. client's servers, Symantec starts to flag ms-playwright-print-deps.exe as malware.

- What is ms-playwright-print-deps.exe?  I can't find a reference to it anywhere in the repo
- Is there anyway to configure playwright installation/my application so this isn't an issue/a thing the system tries to run?

Trying to understand what is happening behind the scenes so I can work with the client's IT department to unblock this exe, or if I can somehow avoid having it called.

**Comment by kblok** [comment]
> What is ms-playwright-print-deps.exe?

print-deps.exe is a tool used to check if the OS has all the dependencies needed to run the browser.

> I can't find a reference to it anywhere in the repo

You can find the code upstream. https://github.com/microsoft/playwright/tree/master/browser_patches/winldd

> Is there anyway to configure playwright installation/my application so this isn't an issue/a thing the system tries to run?
Trying to understand what is happening behind the scenes so I can work with the client's IT department to unblock this exe, or if I can somehow avoid having it called.

One way to avoid that check now would be installing the browsers in a path you will know and then call `LaunchAsync` pass the `executablePath`.

What do you think about this issue @arjunattam?

**Comment by benhysell** [comment]
@kblok Thanks!  Worked like a charm.  I'm happy to close this issue unless there is more conversation to be had around it.

My code in case anyone stumbles here again in the future:
```
 using var playwright = await Playwright.CreateAsync();
 await using var browser = await playwright.Chromium.LaunchAsync(executablePath: @"C:\website\ms-playwright\chromium-799411\chrome-win\chrome.exe);
```

**Comment by kblok** [comment]
Awesome!
Let's wait for @arjunattam's feedback.

**Comment by yury-s** [comment]
> Symantec starts to flag ms-playwright-print-deps.exe as malware.

This is pretty bad it will also bite Playwright (typescript) users, we'll have to do something about it. I'm not sure yet which part makes it look like malware, it might be some of the Win APIs that we call. Maybe there's a way to sign the binary or something to make it look less suspicious.

**Comment by kblok** [comment]
@benhysell would you mind checking if the exe inside this zip runs in your server? thanks!

[PrintDeps.exe.zip](https://github.com/microsoft/playwright-sharp/files/5418426/PrintDeps.exe.zip)

**Comment by benhysell** [comment]
@kblok is that exe in the latest release?  If so I'm happy to pull down the latest NuGet and give it a go.

**Comment by kblok** [comment]
@benhysell we want to be sure that that will fix the issue before shipping a new version.

**Comment by benhysell** [comment]
@kblok Sorry, I can't pull down random exe's from GitHub to run on a client's server.

Going forward I've configured our systems in release to not have to rely on the .exe, this is the safest path for us so I never have to tangle with the anti-virus in the future.

Happy to give it test if/when this gets packaged up.

**Comment by yury-s** [comment]
> @kblok Sorry, I can't pull down random exe's from GitHub to run on a client's server.
> 
That's totally understood.

> Happy to give it test if/when this gets packaged up.

It is currently available in `next` version of our npm: [`playwright@1.5.0-next.1603237992817`](https://www.npmjs.com/package/playwright/v/1.5.0-next.1603237992817). If you can try that, it'd be great.

**Comment by benhysell** [comment]
@yury-s I'm using the NuGet package in my asp.net project...the easiest path for me to test would be if you published a `vNext` version of that.

I do not completely understand the architecture and interdependencies of playwright, i.e.

- I can't find `printdeps.exe` on any of the systems I've installed the NuGet on

- I had a hard finding the file that was getting flagged `ms-playwright-print-deps.exe`, I finally located it in `c:\windows\temp`

Not understating the architecture/interdependencies I'm not apt to go 'off-roading' testing .exes.  Again happy to pull down a NuGet `vNext` and give it a go.

**Comment by yury-s** [comment]
@benhysell  No worries, I think Dario found a way to test it and the fix didn't quite work so we need to investigate further. In any case thanks for looking into this.

> I had a hard finding the file that was getting flagged ms-playwright-print-deps.exe, I finally located it in c:\windows\temp

The file name looks odd to me as well but I'm not too familiar with how it is repackaged in case of NuGet, also it might be the antivirus renamed it or something, the original binary we build is PrintDeps.exe
