### ISSUE TITLE
0.151.0 update seems to be broken on windows

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-sharp#960]
After updating from 0.142.2 running await Playwright.InstallAsync(); will give a 'system cannot find the file specified.' exception on Windows, OSX seems to be OK.

```
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at PlaywrightSharp.Transport.Connection.<InstallAsync>d__21.MoveNext() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 100
```
Note, only had 1 Windows machine available to verify this on but the 0.151.0 folder also does not seem to contain the playwright-driver-win.exe. Not tested with any arguments yet.

Thanks,
-M

**Comment by kababoom** [comment]
A fresh install fixed it.
InstallAsync was failing with the error above, the folder 0.151.0.0 was created but all 3 .exe in it were missing.
The nuget package update was run from OSX, perhaps that caused the issue?

Thanks,
-M

**Comment by kblok** [comment]
@kababoom it must be that. We check for the existence of the folder `0.151.0.0`. We could add the platform in the next release.

**Comment by kababoom** [comment]
@kblok Upgrade from OSX only contained 4 files: browsers.json, ffmpeg.COPYING.GPLv3 +
ffmpeg-mac, playwright-cli without extension.

Thanks,
-M

**Comment by kblok** [comment]
@kababoom can you delete the folder in windows and recreate it?

**Comment by kababoom** [comment]
Works as well.

So it was not the update but the run with OSX that created the folder, then run (from shared folders) on Windows that gave the error since it only checks folder existence.

Thanks,
-M

**Comment by kblok** [comment]
Exactly. In v0.142.2 we checked for the file, but now we have many files so we moved that to check the directory. We could change that.

**Comment by kababoom** [comment]
Or recreate when installAsync fails? or leave as is? (it's now here for reference and only an issue if you build and run it on platform-A then distribute and run it on platform-B). 

So whatever suits you best... 👍 

Thanks,
-M

**Comment by kblok** [comment]
Yeah. I can create an issue for that. That would get you unlocked right?

**Comment by kababoom** [comment]
I'm ok since just leaving it out of distribution fixes it on all 3 platforms we use (osx, ubuntu, win10). In worst case just delete the folder.

Should I close it?

**Comment by kblok** [comment]
Closing in favor of #961
