### ISSUE TITLE
Question: dotnet Global Tool, Update Installed Browsers to latest?

### ISSUE THREAD

**Issue by benhysell** [microsoft/playwright-sharp#969]
I started using the NuGet package 0.142.2 last week in my asp.net core application.  Couple of days ago when 0.151.0 went live I updated my NuGet packages to the latest.  When I attempted to run against playwright I had the following error:

`Failed to launch chromium because executable doesn't exist at C:\\Users\\benh\\AppData\\Local\\ms-playwright\\chromium-815036\\chrome-win\\chrome.exe`

I went down the path of wanting to avoid downloading the browsers at runtime, so I started using the dotnet global tool, `playwright-sharp install-browsers`.  

- Re-ran it...nothing happened, `chromium-799411` still installed
- Deleted the browsers, re-ran the tool, `chromium-799411` installed.

Questions
- I don't see a method to tell the global tool to update the browsers 'to latest', did I miss something somewhere?
- Not knowing the NuGet package upped the required version without a notification caught me off guard.  What is expected by the end developer if they decide they DO NOT want to install browsers at runtime?  Every NuGet update need to install browsers?

**Comment by kblok** [comment]
> I don't see a method to tell the global tool to update the browsers 'to latest', did I miss something somewhere?

We have this issue for that #917 I think we should implement it for the next version.
If you update the dotnet to the latest version you should get the latest browsers.

> Not knowing the NuGet package upped the required version without a notification caught me off guard. What is expected by the end developer if they decide they DO NOT want to install browsers at runtime? Every NuGet update need to install browsers?

What if:
 * You run `playwright-sharp install-browsers` inside the web project.
 * playwright-sharp could try to find a `PlaywrightSharp.dll` and get the version from it.
 * Download the browsers for that version?

**Comment by benhysell** [comment]
- #917 will for sure fix the install issue for the donet global tool.

- I'm ok if it is 'on me' to go and rev the versions of the browsers.  

- Possibly a documentation change to let people know, "Hey if you don't want to install the browsers at run time you are on your own to update the browsers, and they update on every new NuGet release."

- If it is documented I can work it into my workflow to update the browsers on every new NuGet, or I can pin it and always tell playwright "Use this version"

**Comment by kblok** [comment]
@benhysell I would personally expect new browsers if I update Playwright. Most new features require new wires on the browser side. 

> Possibly a documentation change to let people know, "Hey if you don't want to install the browsers at run time you are on your own to update the browsers, and they update on every new NuGet release."

Definitely.

cc @arjunattam

**Comment by benhysell** [comment]
> I would personally expect new browsers if I update Playwright. Most new features require new wires on the browser side.

Do new versions of playwright require new versions of Chrome or is the thinking "Let's always ship the latest and greatest" ?  

I would have thought, naively, yes Chrome adds new things, but core functionality is there and rather static at this point.  

I understand if Chrome releases a new bleeding edge feature I need to go get latest, but minor version bumps I would expect new NuGet packages of playwright would work with whatever version of Chrome I point it at, as long as it is 'recent'.

**Comment by arjunattam** [comment]
Thanks for opening this issue, @benhysell.

At this stage, Playwright versions have a 1-1 mapping with browser versions. This is a combination of requiring browser-side code (e.g. we recently added support for touchscreen taps, which required browser-side changes) and shipping the latest versions (to manage browser upgrades under the Playwright version).

This behavior is influenced by how NPM works in the JS ecosystem. NPM provides a `postinstall` hook to run browser installation whenever the package is installed or updated. This avoids the need for a runtime API (like `InstallAsync`). The dotnet-tool brings this experience to NuGet, but it is independent from the dependency itself.

**Comment by kblok** [comment]
@benhysell Added deployment docs for the upcoming v0.162.0. We will rely on the CLI instead of a dotnet tool to install browsers as part of an app.

Feedback is welcome.

**Comment by benhysell** [comment]
@kblok

-  is the global tool getting deprecated?

- Was the .exe always part of the built application?  I'm not seeing it in the version I'm using
- How large is the .exe?  The DLL is already at 50mb, not looking forward to a larger deploy :-)

**Comment by kblok** [comment]
> is the global tool getting deprecated?

We wouldn't use the global tool for this anymore. Although, I think it would be cool to use the dotnet tool as a bridge to the CLI codegen tool.

> Was the .exe always part of the built application? I'm not seeing it in the version I'm using

It was. But we were unzipping that inside a `playwright-driver` directory at run-time. We would be removing all that boilerplate on v0.162.0.

> How large is the .exe? The DLL is already at 50mb, not looking forward to a larger deploy :-)

We are taking the drivers out of the DLL. That will give us a 500kb DLL file on the next version :-)

**Comment by benhysell** [comment]
I think this will work.  

- Will I have the ability to dictate where the browsers are installed via the cli?  I'm deploying to an onprem machine and my user account can only write to certain directories, I want to make sure I can still tell the cli "put your stuff in this directory."

- I know asking for stability in a pre 1.0 package is asking for a lot, but modifying a bunch of deployment scripts on the next NuGet version is also not desirable on my part.  Kindly asking if 'this is the way', excellent I believe it will work for me.

**Comment by kblok** [comment]
>Will I have the ability to dictate where the browsers are installed via the cli? I'm deploying to an onprem machine and my user account can only write to certain directories, I want to make sure I can still tell the cli "put your stuff in this directory."

You can set the env variable `PLAYWRIGHT_BROWSERS_PATH` before calling the CLI, and then pass that to the `CreateAsync` method.

>I know asking for stability in a pre 1.0 package is asking for a lot, but modifying a bunch of deployment scripts on the next NuGet version is also not desirable on my part. Kindly asking if 'this is the way', excellent I believe it will work for me.

I know it might be quite painful for you as an early adopter, and I really really appreciate your patience. As an early adopter, your feedback is super appreciated. We are trying to provide the best experience for most use case scenarios :)

**Comment by benhysell** [comment]
@kblok appreciate it, appreciate all the effort/hard work!

- I would push, not too hard, but hard, for an input flag on the cli to tell the .exe where to place the browsers much like one can with the dotnet global tool today.  Messing about with environment variables on CI/CD pipelines can be a pain, or has been a pain for me in the past, and I rather not go down that route.  Or allow both...again I'm working on machines where I have limited permissions, the less steps I have to take/things I have to modify the better.

Anyway, I'm happy to close this issue at this point with a 'not going to fix' and point people to the update documents.

**Comment by kblok** [comment]
@benhysell would you mind creating an issue here https://github.com/microsoft/playwright-cli ?
