### ISSUE TITLE
OutputType Library

### ISSUE THREAD

**Issue by Lewka** [microsoft/playwright-sharp#971]
Hello there!
Is it possible to run playwright under OutputType=Library? I'm trying, but all I get the hang test after all. Its hang on line `var playwright = await Playwright.CreateAsync();`. But if I change OutputType to exe then everything works fine.

MyTest is
```	
public class PlaywrightTest {

		[Test]
		public async Task Test()
		{
			Console.WriteLine("Installing playwright");
			await Playwright.InstallAsync();
			Console.WriteLine("Creating playwright");
			var playwright = await Playwright.CreateAsync();
		}
	}
```

* env:  .NetFramework 4.7.2 & Nunit3 3.12

**Comment by kblok** [comment]
Hey @Lewka!
Can you pass me your csproj to test locally?

**Comment by Lewka** [comment]
@kblok https://github.com/Lewka/PlaywrightTest

**Comment by kblok** [comment]
thank you @Lewka

**Comment by kblok** [comment]
@Lewka we were getting this error internally:

>System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Memory`1.get_Span()
   at System.Memory`1.ToArray()
   at PlaywrightSharp.Transport.StdIOTransport.<GetResponseAsync>d__22.MoveNext()

With #974 playwright will report the error instead of getting stuck. But you need to fix those dependencies.
To fix this issue I created the following app.config on your project:


```xml
<configuration>
  <runtime>
	<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
	  <dependentAssembly>
		<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
		<bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.6.0"/>
	  </dependentAssembly>
	  <dependentAssembly>
		<assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
		<bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.3.0"/>
	  </dependentAssembly>
	</assemblyBinding>
  </runtime>
</configuration>
```

**Comment by Lewka** [comment]
@kblok hi. I've added both dependency and app.config file didn't work out though. I've updated the repo, maybe u could tell me what I did wrong.

**Comment by kblok** [comment]
@Lewka could you try adding this redirect?

```xml
<dependentAssembly>
	<assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
	<bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.4.0"/>
</dependentAssembly>
```

**Comment by Lewka** [comment]
@kblok didn't work. anyway, thanks.

**Comment by kblok** [comment]
@Lewka If you upgrade to v0.152.0 you will get better error reporting. Do you want to try that out?
