### ISSUE TITLE
Improve missing browsers message

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-sharp#990]
We are showing the error coming from node. We should translate that

 >"Failed to launch chromium because executable doesn't exist at /Users/neo/Library/Caches/ms-playwright/chromium-815036/chrome-mac/Chromium.app/Contents/MacOS/Chromium\nTry re-installing playwright with \"npm install playwright\"\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs."

**Comment by 304NotModified** [comment]
related https://github.com/microsoft/playwright-dotnet/issues/2239
